#!/usr/bin/env python3
"""Generate src/acospi_const.inc from core-math acospi.c.

Tables extracted:
- T[256][8]   — fast-path polynomial / sqrt-branch table
- T2[128][21] — accurate-path polynomial table (DEGREE+LARGE+2 = 11+8+2)
- Err[256]    — fast-path error bounds
- exceptions[114][2] + exceptions_rnd[114] — accurate-path tiny exceptions
"""
import re, struct, os

SRC = os.path.join(os.path.dirname(__file__), '..', '..', 'core-math', 'src',
                   'binary64', 'acospi', 'acospi.c')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'acospi_const.inc')

with open(SRC) as f:
    text = f.read()

# Strip block comments — acospi.c has /*0x4.6989e4b05fa3p-56,*/ inside T row 0.
text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
# Strip line comments too (after literal hex floats sometimes have // i=0 72.838).
text = re.sub(r'//[^\n]*', '', text)

HEX = re.compile(r'-?0x[0-9a-fA-F.]+p[+-]?\d+')

def to_u64(s):
    v = float.fromhex(s)
    b = struct.pack('<d', v)
    return struct.unpack('<Q', b)[0], v

def extract_block(name, R, C, allow_short=False):
    m = re.search(rf'static const double {name}\[[^\]]+\]\[[^\]]+\]\s*=\s*\{{(.*?)\n\}};',
                  text, re.S)
    assert m, name
    body = m.group(1)
    rows = re.findall(r'\{([^{}]*)\}', body)
    assert len(rows) == R, (name, len(rows), R)
    out = []
    for i, row in enumerate(rows):
        nums = HEX.findall(row)
        if allow_short and len(nums) < C:
            # pad with explicit zero (for T table: rows 192..255 only have 7 cols)
            nums = nums + ['0x0p+0'] * (C - len(nums))
        assert len(nums) == C, (name, i, len(nums), C)
        out.append(nums)
    return out

def extract_array1(name, N):
    m = re.search(rf'static const double {name}\[\d*\]\s*=\s*\{{(.*?)\}}\s*;', text, re.S)
    assert m, name
    nums = HEX.findall(m.group(1))
    assert len(nums) == N, (name, len(nums), N)
    return nums

T = extract_block('T', 256, 8, allow_short=True)
T2 = extract_block('T2', 128, 21)
Err = extract_array1('Err', 256)

# exceptions[][2]
m = re.search(r'static const double exceptions\[[^\]]+\]\[2\]\s*=\s*\{(.*?)\}\s*;',
              text, re.S)
assert m
ex_rows = re.findall(r'\{([^{}]+)\}', m.group(1))
assert len(ex_rows) == 114, len(ex_rows)
ex_pairs = []
for r in ex_rows:
    n = HEX.findall(r)
    assert len(n) == 2
    ex_pairs.append(n)

# exceptions_rnd[114] — int8_t
m = re.search(r'static const int8_t exceptions_rnd\[[^\]]+\]\s*=\s*\{(.*?)\}\s*;',
              text, re.S)
assert m
rnd_nums = re.findall(r'-?\d+', m.group(1))
assert len(rnd_nums) == 114, len(rnd_nums)

lines = ["// Auto-generated by tools/acospi_gen.py — do not edit by hand.",
         "// Source: core-math/src/binary64/acospi/acospi.c", ""]

def emit_2d(name, rows, comment=''):
    R, C = len(rows), len(rows[0])
    if comment:
        lines.append(f"  // {name} {comment}")
    lines.append(f"  {name}: array[0..{R-1},0..{C-1}] of Tb64u64 = (")
    for i, row in enumerate(rows):
        ents = []
        for n in row:
            u, _ = to_u64(n)
            ents.append(f"(u:${u:016X})")
        sep = ',' if i < R-1 else ''
        lines.append(f"    ({', '.join(ents)}){sep}")
    lines.append("  );")
    lines.append("")

def emit_1d(name, nums, comment=''):
    if comment:
        lines.append(f"  // {name} {comment}")
    lines.append(f"  {name}: array[0..{len(nums)-1}] of Tb64u64 = (")
    for i, n in enumerate(nums):
        u, _ = to_u64(n)
        sep = ',' if i < len(nums)-1 else ''
        lines.append(f"    (u:${u:016X}){sep}")
    lines.append("  );")
    lines.append("")

def emit_int8(name, nums, comment=''):
    if comment:
        lines.append(f"  // {name} {comment}")
    lines.append(f"  {name}: array[0..{len(nums)-1}] of ShortInt = (")
    # 16 per line
    for i in range(0, len(nums), 16):
        chunk = ', '.join(nums[i:i+16])
        sep = ',' if i+16 < len(nums) else ''
        lines.append(f"    {chunk}{sep}")
    lines.append("  );")
    lines.append("")

emit_2d('cAcospiT',  T,  '[256][8] fast-path polynomial & sqrt-branch tables')
emit_2d('cAcospiT2', T2, '[128][21] accurate-path polynomial table (DEGREE+LARGE+2)')
emit_1d('cAcospiErr', Err, '[256] fast-path Ziv error bounds')
emit_2d('cAcospiEx',  ex_pairs, '[114][2] accurate-path exception (input, hi)')
emit_int8('cAcospiExRnd', rnd_nums, '[114] exception rounding direction (-1, 0, 1)')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"wrote {OUT}: {sum(1 for _ in open(OUT))} lines")
