#!/usr/bin/env python3
"""Generate src/asinpi_const.inc from core-math/src/binary64/asinpi/asinpi.c.

Tables emitted (using TUInt128 for u128 pairs):
  cAsinpi_pasin_b[4]      u64
  cAsinpi_pasin_ch[4]     u128 pairs
  cAsinpi_acc_s[64]       u128 pairs (asinpi_acc)
  cAsinpi_main_s[65]      u64
  cAsinpi_main_sh[65]     u64
  cAsinpi_main_a[4]       u64
  cAsinpi_main_b[5]       u64
  cAsinpi_main_ch[4]      doubles
  cAsinpi_small_exc[18][3]  doubles (asinpi_small exception triples)
  Plus scalar constants.
"""
import re, struct, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'asinpi', 'asinpi.c')
OUT  = os.path.join(ROOT, 'src', 'inc_64', 'asinpi_const_64.inc')

text = open(SRC).read()

def b64hex(s):
    f = float.fromhex(s)
    return struct.unpack('<Q', struct.pack('<d', f))[0]

def fu(u):
    s = f"${u:016X}"
    if u >= (1 << 63):
        return f"QWord({s})"
    return s

# Slice array body by name: "<name>[]... = { ... };"
def slice_body(pat):
    m = re.search(pat, text)
    assert m, pat
    i = m.end() - 1   # at the '{'
    depth = 0
    j = i
    while j < len(text):
        if text[j] == '{':
            depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0:
                return text[i:j+1]
        j += 1
    raise SystemExit('mismatched braces')

# pasin helper: b[] is u64 inside pasin
m = re.search(r'static u128 pasin\(u128 x\)\{[^}]*?u64 b\[\] = \{([^}]*)\};', text, re.S)
PASIN_B = [int(v.strip(), 16) for v in m.group(1).split(',') if v.strip()]
assert len(PASIN_B) == 4

m = re.search(r'static u128 pasin\(u128 x\)\{.*?u128_u ch\[\] = \{(.*?)\};', text, re.S)
ch_text = m.group(1)
PASIN_CH = []
for entry in re.finditer(r'\.bl\s*=\s*0x([0-9a-fA-F]+).*?\.bh\s*=\s*0x([0-9a-fA-F]+)', ch_text):
    PASIN_CH.append((int(entry.group(1), 16), int(entry.group(2), 16)))
assert len(PASIN_CH) == 4

# asinpi_acc: u128_u s[]
m = re.search(r'asinpi_acc\(double x\)\{.*?static const u128_u s\[\] =(.*?);', text, re.S)
ACC_S_TEXT = m.group(1)
ACC_S = []
for entry in re.finditer(r'\.bl\s*=\s*0x([0-9a-fA-F]+),\s*\.bh\s*=\s*0x([0-9a-fA-F]+)', ACC_S_TEXT):
    ACC_S.append((int(entry.group(1), 16), int(entry.group(2), 16)))
assert len(ACC_S) == 63, len(ACC_S)

# Main: s[] u64 (65 entries, last one ~0ull>>1 = 0x7fffffffffffffff)
m = re.search(r'cr_asinpi\(double x\)\{.*?static const u64 s\[\] = \{(.*?)\};', text, re.S)
S_TEXT = m.group(1)
nums = re.findall(r'(?:0x[0-9a-fA-F]+|~0ull>>1|\b0\b)', S_TEXT)
MAIN_S = []
for n in nums:
    if n == '~0ull>>1':
        MAIN_S.append(0x7fffffffffffffff)
    elif n == '0':
        MAIN_S.append(0)
    else:
        MAIN_S.append(int(n, 16))
assert len(MAIN_S) == 65, len(MAIN_S)

# Main: sh[] u64 (65 entries, last is bare 0)
m = re.search(r'static const u64 sh\[\] = \{(.*?)\};', text, re.S)
SH_TEXT = m.group(1)
nums = re.findall(r'0x[0-9a-fA-F]+|\b0\b', SH_TEXT)
MAIN_SH = [0 if v == '0' else int(v, 16) for v in nums]
assert len(MAIN_SH) == 65, len(MAIN_SH)

# Main: a[4]
m_iter = list(re.finditer(r'static const u64 a\[\] = \{([^}]*)\};', text))
assert len(m_iter) == 1
MAIN_A = [int(v.strip(), 16) for v in m_iter[0].group(1).split(',') if v.strip()]
assert len(MAIN_A) == 4

# Main: b[5] (pasin has b[4] but it's "static const u64 b[]" too — last occurrence is main)
m_iter = list(re.finditer(r'static const u64 b\[\] = \{([^}]*)\};', text))
# Find the 5-element one
MAIN_B = None
for mi in m_iter:
    vals = [int(v.strip(), 16) for v in mi.group(1).split(',') if v.strip()]
    if len(vals) == 5:
        MAIN_B = vals
        break
assert MAIN_B is not None and len(MAIN_B) == 5

# Main: ch[4]
m = re.search(r'static const double ch\[\] = \{([^}]*)\};', text)
MAIN_CH_TEXT = m.group(1)
MAIN_CH = [b64hex(v) for v in re.findall(r'-?0x[0-9a-fA-F.p+\-]+', MAIN_CH_TEXT)]
assert len(MAIN_CH) == 4

# asinpi_small exceptions[18][3]
m = re.search(r'asinpi_small.*?exceptions\[EXCEPTIONS\]\[3\] = \{(.*?)\};', text, re.S)
EX_TEXT = m.group(1)
SMALL_EXC = []
for row in re.finditer(r'\{([^{}]+)\}', EX_TEXT):
    vals = re.findall(r'-?0x[0-9a-fA-F.p+\-]+', row.group(1))
    assert len(vals) == 3
    SMALL_EXC.append([b64hex(v) for v in vals])
assert len(SMALL_EXC) == 18, len(SMALL_EXC)

# Scalar constants
INV_PI_H = 0x517cc1b727220a94
INV_PI_L = 0xfe13abe8fa9a6ee0
ONE_OVER_PIH = b64hex('0x1.45f306dc9c883p-2')
ONE_OVER_PIL = b64hex('-0x1.6b01ec5417056p-56')
X1           = b64hex('0x1.fff8133aa33e4p-1')
SMALL_C1H    = b64hex('0x1.45f306dc9c883p-2')
SMALL_C1L    = b64hex('-0x1.6b01ec5417057p-56')
SMALL_C3     = b64hex('0x1.b2995e7b7b606p-5')

lines = []
lines.append('// Auto-generated by tools/asinpi_gen.py — DO NOT EDIT BY HAND.')
lines.append('// Source: core-math/src/binary64/asinpi/asinpi.c')
lines.append('')
lines.append('const')
lines.append(f'  cAsinpi_INV_PI_H:    UInt64  = {fu(INV_PI_H)};')
lines.append(f'  cAsinpi_INV_PI_L:    UInt64  = {fu(INV_PI_L)};')
lines.append(f'  cAsinpi_ONE_OVER_PI_H: Tb64u64 = (u: {fu(ONE_OVER_PIH)});')
lines.append(f'  cAsinpi_ONE_OVER_PI_L: Tb64u64 = (u: {fu(ONE_OVER_PIL)});')
lines.append(f'  cAsinpi_X1:          Tb64u64 = (u: {fu(X1)});')
lines.append(f'  cAsinpi_Small_C1H:   Tb64u64 = (u: {fu(SMALL_C1H)});')
lines.append(f'  cAsinpi_Small_C1L:   Tb64u64 = (u: {fu(SMALL_C1L)});')
lines.append(f'  cAsinpi_Small_C3:    Tb64u64 = (u: {fu(SMALL_C3)});')
lines.append('')

lines.append('  // pasin: b[4] u64')
lines.append('  cAsinpi_PasinB: array[0..3] of UInt64 = (')
lines.append('    ' + ', '.join(fu(v) for v in PASIN_B))
lines.append('  );')
lines.append('')
lines.append('  // pasin: ch[4] u128 pairs')
lines.append('  cAsinpi_PasinCh: array[0..3] of TUInt128 = (')
for i, (lo, hi) in enumerate(PASIN_CH):
    sep = ',' if i + 1 < 4 else ''
    lines.append(f'    (lo: {fu(lo)}; hi: {fu(hi)}){sep}')
lines.append('  );')
lines.append('')

lines.append('  // asinpi_acc: s[63] u128 pairs')
lines.append('  cAsinpi_AccS: array[0..62] of TUInt128 = (')
for i, (lo, hi) in enumerate(ACC_S):
    sep = ',' if i + 1 < 63 else ''
    lines.append(f'    (lo: {fu(lo)}; hi: {fu(hi)}){sep}')
lines.append('  );')
lines.append('')

lines.append('  // main: s[65] u64')
lines.append('  cAsinpi_MainS: array[0..64] of UInt64 = (')
for i in range(0, 65, 4):
    chunk = MAIN_S[i:i+4]
    s = ', '.join(fu(v) for v in chunk)
    sep = ',' if i + 4 < 65 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')

lines.append('  // main: sh[65] u64')
lines.append('  cAsinpi_MainSh: array[0..64] of UInt64 = (')
for i in range(0, 65, 4):
    chunk = MAIN_SH[i:i+4]
    s = ', '.join(fu(v) for v in chunk)
    sep = ',' if i + 4 < 65 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')

lines.append('  // main: a[4] u64')
lines.append('  cAsinpi_MainA: array[0..3] of UInt64 = (')
lines.append('    ' + ', '.join(fu(v) for v in MAIN_A))
lines.append('  );')
lines.append('')

lines.append('  // main: b[5] u64')
lines.append('  cAsinpi_MainB: array[0..4] of UInt64 = (')
lines.append('    ' + ', '.join(fu(v) for v in MAIN_B))
lines.append('  );')
lines.append('')

lines.append('  // Phase 6.4/B: cAsinpi_MainCh[0..3] lifted to named Tb64u64 scalars')
lines.append('  // (read only as `.f` from asinpi_port_64.inc).')
for i, v in enumerate(MAIN_CH):
    lines.append(f'  cAsinpi_MainCh_{i}: Tb64u64 = (u: {fu(v)});')
lines.append('')

lines.append('  // Phase 6.4/A+B: asinpi_small 18 exception triples lifted to')
lines.append('  // cAsinpi_SmallExc{X,H,L}_<i> named Tb64u64 scalars; the')
lines.append('  // sign-branched unrolled match list in Asinpi_Small reads them')
lines.append('  // with literal indices.')
for i, r in enumerate(SMALL_EXC):
    lines.append(f'  cAsinpi_SmallExcX_{i:02d}: Tb64u64 = (u: {fu(r[0])});')
lines.append('')
for i, r in enumerate(SMALL_EXC):
    lines.append(f'  cAsinpi_SmallExcH_{i:02d}: Tb64u64 = (u: {fu(r[1])});')
lines.append('')
for i, r in enumerate(SMALL_EXC):
    lines.append(f'  cAsinpi_SmallExcL_{i:02d}: Tb64u64 = (u: {fu(r[2])});')
lines.append('')

open(OUT, 'w').write('\n'.join(lines) + '\n')
print(f'Wrote {OUT}: pasinB={len(PASIN_B)} pasinCh={len(PASIN_CH)} accS={len(ACC_S)} mainS={len(MAIN_S)} mainSh={len(MAIN_SH)} mainA={len(MAIN_A)} mainB={len(MAIN_B)} mainCh={len(MAIN_CH)} smallExc={len(SMALL_EXC)}')
