#!/usr/bin/env python3
"""Generate src/atan2pi_const.inc from core-math/src/binary64/atan2pi/atan2pi.c.

Emits:
  cAtan2piPFast[65*10]  — Pfast polynomial coefficients (flat)
  cAtan2piXfast[65]
  cAtan2piErrFast[65]
  ONE_OVER_PI_H/L doubles (constants)
  P9 (degree-9 coefficient for i=0)
The P[30]/Q[30] tint tables and ONE/ONE_HALF/ONE_OVER_PI tint constants are
*not* emitted — atan2pi reuses cAtan2P/cAtan2Q from atan2_const.inc and the
TINT_ONE / TINT_ONE_HALF / TINT_ONE_OVER_PI constants from pascoremathtypes.
"""
import re, struct, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'atan2pi', 'atan2pi.c')
OUT  = os.path.join(ROOT, 'src', 'atan2pi_const.inc')

text = open(SRC).read()

def b64(s):
    f = float.fromhex(s)
    return struct.unpack('<Q', struct.pack('<d', f))[0]

def fu(u): return f"${u:016X}"

def slice_array(name):
    m = re.search(rf'\b{re.escape(name)}\b\s*(?:\[[^\]]*\]\s*)+=\s*\{{', text)
    assert m, name
    i = m.end() - 1
    depth = 0
    j = i
    while j < len(text):
        if text[j] == '{':
            depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0:
                return text[i:j+1]
        j += 1
    raise SystemExit('mismatched braces')

# Pfast[65][10]
pf_block = slice_array('Pfast')
# Strip /* ... */ comments so we don't pick up "0x1.c6e5d41706f0dp-4" inside the i=0 comment.
pf_clean = re.sub(r'/\*.*?\*/', '', pf_block, flags=re.S)
rows = re.findall(r'\{([^{}]+)\}', pf_clean)
assert len(rows) == 65, len(rows)
PFAST = []
for r in rows:
    nums = re.findall(r'-?0x[0-9a-fA-F.p+\-]+|-?\d+\.\d+|-?\b0\b', r)
    assert len(nums) == 10, (r, nums)
    def _conv(v):
        if v in ('0','-0'): return 0
        if v.startswith(('0x','-0x','+0x')): return b64(v)
        # decimal literal like "1.0"
        return struct.unpack('<Q', struct.pack('<d', float(v)))[0]
    PFAST.append([_conv(v) for v in nums])

# Xfast[65]
xf_block = slice_array('Xfast')
xf_clean = re.sub(r'/\*.*?\*/', '', xf_block, flags=re.S)
xf_vals = re.findall(r'-?0x[0-9a-fA-F.p+\-]+|-?\b0\b', xf_clean)
assert len(xf_vals) == 65, len(xf_vals)
XFAST = [0 if v in ('0','-0') else b64(v) for v in xf_vals]

# err_fast[65]
ef_block = slice_array('err_fast')
ef_clean = re.sub(r'/\*.*?\*/', '', ef_block, flags=re.S)
ef_vals = re.findall(r'-?0x[0-9a-fA-F.p+\-]+', ef_clean)
assert len(ef_vals) == 65, len(ef_vals)
ERR = [b64(v) for v in ef_vals]

# Constants
ONE_OVER_PI_H = b64('0x1.45f306dc9c883p-2')
ONE_OVER_PI_L = b64('-0x1.6b01ec5417056p-56')
P9            = b64('0x1.c6e5d41706f0dp-4')

lines = []
lines.append('// Auto-generated by tools/atan2pi_gen.py — DO NOT EDIT BY HAND.')
lines.append('// Source: core-math/src/binary64/atan2pi/atan2pi.c')
lines.append('')
lines.append('const')
lines.append('  // 1/pi double-double')
lines.append(f'  cAtan2piOneOverPiH: Tb64u64 = (u: {fu(ONE_OVER_PI_H)}); //  0x1.45f306dc9c883p-2')
lines.append(f'  cAtan2piOneOverPiL: Tb64u64 = (u: {fu(ONE_OVER_PI_L)}); // -0x1.6b01ec5417056p-56')
lines.append(f'  cAtan2piP9:         Tb64u64 = (u: {fu(P9)}); //  0x1.c6e5d41706f0dp-4 (i=0 degree-9 coeff)')
lines.append('')
# Pfast: flat 650 entries, row-major (row i column j = entry [10*i + j])
lines.append('  // Pfast[i][j] = cAtan2piPFast[10*i + j], 65 rows of 10')
lines.append('  cAtan2piPFast: array[0..649] of Tb64u64 = (')
flat = []
for row in PFAST:
    flat.extend(row)
for i in range(0, 650, 5):
    chunk = flat[i:i+5]
    s = ', '.join(f'(u:{fu(u)})' for u in chunk)
    sep = ',' if i + 5 < 650 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')
# Xfast
lines.append('  cAtan2piXfast: array[0..64] of Tb64u64 = (')
for i in range(0, 65, 5):
    chunk = XFAST[i:i+5]
    s = ', '.join(f'(u:{fu(u)})' for u in chunk)
    sep = ',' if i + 5 < 65 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')
# ErrFast
lines.append('  cAtan2piErrFast: array[0..64] of Tb64u64 = (')
for i in range(0, 65, 5):
    chunk = ERR[i:i+5]
    s = ', '.join(f'(u:{fu(u)})' for u in chunk)
    sep = ',' if i + 5 < 65 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')

open(OUT, 'w').write('\n'.join(lines) + '\n')
print(f'Wrote {OUT}: PFast={len(PFAST)}x10 Xfast={len(XFAST)} ErrFast={len(ERR)}')
