#!/usr/bin/env python3
"""Generate src/atan2_const.inc from core-math/src/binary64/atan2/atan2.c.

Emits:
  cAtan2P, cAtan2Q   — TInt64 polynomial coefficients (30 entries each)
  cAtan2T2           — 65 doubles (Tb64u64 array)
  cAtan2F2           — 65 (lo, hi) Double pairs (Tb64u64 array of 130)
  cAtan2O            — 8 (lo, hi) double pairs (Tb64u64 array of 16)
  cAtan2B            — 3 fast-polynomial coeffs
  cAtan2B2           — 4 refine-polynomial coeffs
"""
import re, struct, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'atan2', 'atan2.c')
OUT  = os.path.join(ROOT, 'src', 'atan2_const.inc')

text = open(SRC).read()

def b64(s):
    f = float.fromhex(s)
    return struct.unpack('<Q', struct.pack('<d', f))[0]

def fu(u): return f"${u:016X}"

def slice_array(name):
    m = re.search(rf'\b{re.escape(name)}\b\s*(?:\[[^\]]*\]\s*)+=\s*\{{', text)
    assert m, name
    i = m.end() - 1
    depth = 0
    j = i
    while j < len(text):
        if text[j] == '{':
            depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0:
                return text[i:j+1]
        j += 1
    raise SystemExit('mismatched braces')

# Parse P[30] / Q[30] tint_t
def parse_tints(name):
    block = slice_array(name)
    structs = re.findall(r'\{\.h=([^,]+),\s*\.m=([^,]+),\s*\.l=([^,]+),\s*\.ex=(-?\d+),\s*\.sgn=(\d+)\s*\}', block)
    assert len(structs) == 30, (name, len(structs))
    out = []
    for h, m, l, ex, sgn in structs:
        out.append((int(h, 0), int(m, 0), int(l, 0), int(ex), int(sgn)))
    return out

P = parse_tints('P')
Q = parse_tints('Q')

# T2[65] (single doubles)
t2_block = slice_array('T2')
t2_vals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', t2_block)
assert len(t2_vals) == 65, len(t2_vals)
T2 = [b64(v) for v in t2_vals]

# f2[65][2] — pairs (lo, hi)
f2_block = slice_array('f2')
pairs = re.findall(r'\{([^{}]+)\}', f2_block)
assert len(pairs) == 65, len(pairs)
F2 = []
for p in pairs:
    nums = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', p)
    if len(nums) == 0:
        # {0p+0, 0p+0} would parse fine — but the literal is "0x0p+0"
        nums = re.findall(r'-?0(?:x[0-9a-fA-F.p+\-]+)?', p)
    assert len(nums) == 2, p
    F2.append((b64(nums[0]), b64(nums[1])))

# O[8][2] — pairs (lo, hi)? Looking at C: {0,0}, {0x1.921...p+0, 0x1.1a6...p-54},
# Actually the order is { lit1, lit2 }: lit1 is the high (used as fh += O[kw][0]),
# lit2 the low (fl += O[kw][1]). We mirror order.
o_block = slice_array('O')
o_pairs = re.findall(r'\{([^{}]+)\}', o_block)
assert len(o_pairs) == 8, len(o_pairs)
O = []
for p in o_pairs:
    # Replace bare "0" with "0x0p+0" for parser convenience
    nums = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+|-?\b0\b', p)
    assert len(nums) == 2, p
    def conv(v):
        if v == '0' or v == '-0': return 0
        return b64(v)
    O.append((conv(nums[0]), conv(nums[1])))

# b[3], b2[4]
b_block = slice_array('b')
b_vals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', b_block)
assert len(b_vals) == 3, b_vals
B = [b64(v) for v in b_vals]

b2_block = slice_array('b2')
b2_vals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', b2_block)
assert len(b2_vals) == 4, b2_vals
B2 = [b64(v) for v in b2_vals]

# Format
def fmt_tint(rec):
    h, m, l, ex, sgn = rec
    return f'(m:{fu(m)}; h:{fu(h)}; l:{fu(l)}; ex:{ex}; sgn:{sgn})'

lines = []
lines.append('// Auto-generated by tools/atan2_gen.py — DO NOT EDIT BY HAND.')
lines.append('// Source: core-math/src/binary64/atan2/atan2.c')
lines.append('')
lines.append('const')
lines.append('  cAtan2P: array[0..29] of TInt64 = (')
for i in range(30):
    sep = ',' if i < 29 else ''
    lines.append(f'    {fmt_tint(P[i])}{sep}')
lines.append('  );')
lines.append('')
lines.append('  cAtan2Q: array[0..29] of TInt64 = (')
for i in range(30):
    sep = ',' if i < 29 else ''
    lines.append(f'    {fmt_tint(Q[i])}{sep}')
lines.append('  );')
lines.append('')
# T2 [65]
lines.append('  cAtan2T2: array[0..64] of Tb64u64 = (')
for i in range(0, 65, 4):
    chunk = T2[i:i+4]
    s = ', '.join(f'(u:{fu(u)})' for u in chunk)
    sep = ',' if i + 4 < 65 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')
# F2 [65][2] — flat array of 130 Tb64u64, F2[2*i]=lo, F2[2*i+1]=hi
lines.append('  // f2[i][0] = lo (= cAtan2F2[2*i]), f2[i][1] = hi (= cAtan2F2[2*i+1])')
lines.append('  cAtan2F2: array[0..129] of Tb64u64 = (')
flat = []
for lo, hi in F2:
    flat.extend([lo, hi])
for i in range(0, 130, 4):
    chunk = flat[i:i+4]
    s = ', '.join(f'(u:{fu(u)})' for u in chunk)
    sep = ',' if i + 4 < 130 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')
# O [8][2] — flat 16
lines.append('  // O[i][0] = first slot (= cAtan2O[2*i]), O[i][1] = second (= cAtan2O[2*i+1])')
lines.append('  cAtan2O: array[0..15] of Tb64u64 = (')
oflat = []
for a, b in O:
    oflat.extend([a, b])
for i in range(0, 16, 4):
    chunk = oflat[i:i+4]
    s = ', '.join(f'(u:{fu(u)})' for u in chunk)
    sep = ',' if i + 4 < 16 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')
# B[3], B2[4]
lines.append('  cAtan2B: array[0..2] of Tb64u64 = (')
lines.append('    ' + ', '.join(f'(u:{fu(u)})' for u in B))
lines.append('  );')
lines.append('')
lines.append('  cAtan2B2: array[0..3] of Tb64u64 = (')
lines.append('    ' + ', '.join(f'(u:{fu(u)})' for u in B2))
lines.append('  );')
lines.append('')

open(OUT, 'w').write('\n'.join(lines) + '\n')
print(f'Wrote {OUT}: P={len(P)} Q={len(Q)} T2={len(T2)} F2={len(F2)} O={len(O)} B={len(B)} B2={len(B2)}')
