#!/usr/bin/env python3
"""Generate src/inc_64/erf_const_64.inc by extracting tables from core-math erf.c.

Tables extracted:
- C[94][13] (fast-path polynomial coefficients) — runtime-indexed; emitted as Tb64u64 array.
- C2[47][27] (accurate-path polynomial coefficients) — runtime-indexed; array.
- erf0 (degree-11 polynomial for fast-path z<1/16; cErfC0) — Phase 6.6 Pillar B
  named scalars cErfC0_0..7 (every read in port is .f and literal-indexed after unroll).
- erf0_accurate (p[]; cErfP) — Phase 6.6 Pillar B named scalars cErfP_0..14.
- exceptions_tiny (171 triples; cErfExTiny) — runtime-indexed (binary search); array.
- exceptions_accurate (5 triples; cErfExAcc) — Phase 6.6 Pillar B named scalars
  cErfExAcc_0_0..4_2 (loop unrolled in port).

All hex floats are decoded with float.fromhex() and re-encoded as Tb64u64
records via struct.pack to avoid hand-typing bit patterns.
"""
import re, struct, sys, os

SRC = os.path.join(os.path.dirname(__file__), '..', '..', 'core-math', 'src',
                   'binary64', 'erf', 'erf.c')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'inc_64',
                   'erf_const_64.inc')

with open(SRC) as f:
    text = f.read()

HEX = re.compile(r'-?0x[0-9a-fA-F.]+p[+-]?\d+')

def to_u64(s):
    v = float.fromhex(s)
    b = struct.pack('<d', v)
    return struct.unpack('<Q', b)[0], v

def fu(u):
    """Format a u64 as the inner of (u:...) — wrap in QWord(...) if bit-63 is set."""
    if u >> 63:
        return f"QWord(${u:016X})"
    return f"${u:016X}"

def fmt_rec(s):
    u, _v = to_u64(s)
    return f"(u:{fu(u)})"

def extract_block(name, num_rows, num_cols):
    """Extract a `static const double NAME[..][..] = { ... };` block."""
    m = re.search(rf'static const double {name}\[\d+\]\[\d+\] = \{{(.*?)\n\}};', text, re.S)
    assert m, name
    body = m.group(1)
    rows = re.findall(r'\{([^{}]*)\}', body)
    assert len(rows) == num_rows, (name, len(rows), num_rows)
    out = []
    for i, row in enumerate(rows):
        nums = HEX.findall(row)
        assert len(nums) == num_cols, (name, i, len(nums), num_cols)
        out.append(nums)
    return out

def extract_named_array(name, count):
    m = re.search(rf'static const double {name}\[\] = \{{(.*?)\n\s*\}};', text, re.S)
    assert m, name
    nums = HEX.findall(m.group(1))
    assert len(nums) == count, (name, len(nums), count)
    return nums

def extract_exception_block(after_marker, count):
    """Find static const double exceptions[][3] AFTER a given function-name marker."""
    idx = text.index(after_marker)
    sub = text[idx:]
    m = re.search(r'static const double exceptions\[\]\[3\] = \{(.*?)\n\s*\}\s*;', sub, re.S)
    assert m, after_marker
    body = m.group(1)
    rows = re.findall(r'\{([^{}]+)\}', body)
    assert len(rows) == count, (after_marker, len(rows), count)
    out = []
    for r in rows:
        nums = HEX.findall(r)
        assert len(nums) == 3
        out.append(nums)
    return out

C = extract_block('C', 94, 13)
C2 = extract_block('C2', 47, 27)
ex_tiny = extract_exception_block('cr_erf_accurate_tiny', 171)
ex_acc = extract_exception_block('cr_erf_accurate ', 5)

# erf0 polynomial in cr_erf_fast (z<1/16)
m = re.search(r'static const double c0\[\] = \{(.*?)\};', text, re.S)
c0_nums = HEX.findall(m.group(1))
assert len(c0_nums) == 8, len(c0_nums)

# accurate p[] polynomial (after the tiny exceptions block)
p_nums = extract_named_array('p', 15)

lines = ["// Auto-generated by tools/erf_gen.py — do not edit by hand.",
         "// Source: core-math/src/binary64/erf/erf.c", ""]

def emit_named_scalars(prefix, nums, comment=''):
    """Emit Tb64u64 named scalars cPrefix_0..N-1 (Phase 6.6 Pillar B)."""
    if comment:
        lines.append(f"  // {prefix}_<i>{(' ' + comment) if comment else ''}")
    for i, n in enumerate(nums):
        u, _ = to_u64(n)
        lines.append(f"  {prefix}_{i}: Tb64u64 = (u:{fu(u)});  // {n}")
    lines.append("")

def emit_named_2d(prefix, rows, comment=''):
    """Emit Tb64u64 named scalars cPrefix_<i>_<j> (Phase 6.6 Pillar B)."""
    if comment:
        lines.append(f"  // {prefix}_<i>_<j>{(' ' + comment) if comment else ''}")
    for i, row in enumerate(rows):
        for j, n in enumerate(row):
            u, _ = to_u64(n)
            lines.append(f"  {prefix}_{i}_{j}: Tb64u64 = (u:{fu(u)});  // {n}")
    lines.append("")

def emit_array2(name, rows, dim_comment=''):
    R = len(rows); C_ = len(rows[0])
    lines.append(f"  // {name}{(' ' + dim_comment) if dim_comment else ''}")
    lines.append(f"  {name}: array[0..{R-1},0..{C_-1}] of Tb64u64 = (")
    for i, row in enumerate(rows):
        ents = [fmt_rec(n) for n in row]
        sep = ',' if i < R-1 else ''
        lines.append(f"    ({', '.join(ents)}){sep}  // i={i+1}")
    lines.append("  );")
    lines.append("")

# Pillar B named scalars (literal-indexed in port after Pillar A unroll).
emit_named_scalars('cErfC0', c0_nums, '(degree-11 fast polynomial, z<1/16)')
emit_named_scalars('cErfP', p_nums, '(degree-21 accurate polynomial, z<1/8)')

# Runtime-indexed tables stay as 2D arrays.
emit_array2('cErfC', C, '[94][13] fast-path polynomial table')
emit_array2('cErfC2', C2, '[47][27] accurate-path polynomial table')
emit_array2('cErfExTiny', ex_tiny, '[171][3] tiny-z exception triples')

# Pillar B 2D named scalars (loop over i unrolled in port).
emit_named_2d('cErfExAcc', ex_acc, '(5 accurate-z exception triples)')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"wrote {OUT}: {sum(1 for _ in open(OUT))} lines")
