#!/usr/bin/env python3
"""Generate src/inc_64/erfc_const_64.inc by extracting tables from core-math erfc.c.

Tables extracted:
- T[6][13]            : asympt fast-path polynomials (cErfcT) — runtime-indexed; array.
- Tacc[10][30]        : asympt accurate-path polynomials (cErfcTacc) — runtime-indexed; array.
- E2[28]              : degree-19 accurate exp polynomial (cErfcE2) — array (used by polydd loops).
- exceptions in erfc_asympt_accurate (22 triples) — Phase 6.6 Pillar B
  named scalars cErfcAsymptEx_<i>_<j> (loop unrolled in port).
- exceptions in cr_erfc_accurate negative branch (17 triples) — Pillar B
  cErfcAccNegEx_<i>_<j> (loop unrolled).
- exceptions in cr_erfc_accurate positive branch (29 triples) — Pillar B
  cErfcAccPosEx_<i>_<j> (loop unrolled).

All hex floats are decoded with float.fromhex() and re-encoded as Tb64u64
records via struct.pack to avoid hand-typing bit patterns.
"""
import re, struct, os

SRC = os.path.join(os.path.dirname(__file__), '..', '..', 'core-math', 'src',
                   'binary64', 'erfc', 'erfc.c')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'inc_64',
                   'erfc_const_64.inc')

with open(SRC) as f:
    text = f.read()

HEX = re.compile(r'-?0x[0-9a-fA-F.]+p[+-]?\d+')

def to_u64(s):
    v = float.fromhex(s)
    b = struct.pack('<d', v)
    return struct.unpack('<Q', b)[0], v

def fu(u):
    if u >> 63:
        return f"QWord(${u:016X})"
    return f"${u:016X}"

# ---- T[6][13] ----
m = re.search(r'static const double T\[6\]\[13\] = \{(.*?)\n\};', text, re.S)
assert m, 'T'
T_rows = re.findall(r'\{([^{}]*)\}', m.group(1))
assert len(T_rows) == 6
T = []
for row in T_rows:
    nums = HEX.findall(row)
    assert len(nums) == 13
    T.append(nums)

# ---- Tacc[10][30] (variable-degree polynomials, shorter rows zero-padded) ----
m = re.search(r'static const double Tacc\[10\]\[30\] = \{(.*?)\n\};', text, re.S)
assert m, 'Tacc'
Tacc_rows = re.findall(r'\{([^{}]*)\}', m.group(1))
assert len(Tacc_rows) == 10
Tacc = []
for row in Tacc_rows:
    nums = HEX.findall(row)
    while len(nums) < 30:
        nums.append('0x0p+0')
    Tacc.append(nums)

# ---- E2[] ----
m = re.search(r'static const double E2\[\] = \{(.*?)\n\};', text, re.S)
assert m, 'E2'
E2_nums = HEX.findall(m.group(1))
assert len(E2_nums) == 28, len(E2_nums)

# ---- exception tables ----
def extract_after(marker_func_name, count, dim=3):
    idx = text.index(marker_func_name)
    sub = text[idx:]
    m = re.search(r'static const double exceptions\[(?:\d*)?\]\[3\] = \{(.*?)\n\s*\}\s*;', sub, re.S)
    assert m, marker_func_name
    rows = re.findall(r'\{([^{}]+)\}', m.group(1))
    assert len(rows) == count, (marker_func_name, len(rows), count)
    out = []
    for r in rows:
        nums = HEX.findall(r)
        assert len(nums) == dim
        out.append(nums)
    return out

ex_asympt = extract_after('erfc_asympt_accurate', 22)

cra_idx = text.index('cr_erfc_accurate (double x)')
sub = text[cra_idx:]
m1 = re.search(r'static const double exceptions\[\]\[3\] = \{(.*?)\n\s*\}\s*;', sub, re.S)
assert m1
rows = re.findall(r'\{([^{}]+)\}', m1.group(1))
assert len(rows) == 17, len(rows)
ex_neg = []
for r in rows:
    nums = HEX.findall(r)
    assert len(nums) == 3
    ex_neg.append(nums)

sub2 = sub[m1.end():]
m2 = re.search(r'static const double exceptions\[\]\[3\] = \{(.*?)\n\s*\}\s*;', sub2, re.S)
assert m2
rows = re.findall(r'\{([^{}]+)\}', m2.group(1))
assert len(rows) == 29, len(rows)
ex_pos = []
for r in rows:
    nums = HEX.findall(r)
    assert len(nums) == 3
    ex_pos.append(nums)

# ---- emit ----
lines = ["// Auto-generated by tools/erfc_gen.py — do not edit by hand.",
         "// Source: core-math/src/binary64/erfc/erfc.c", ""]

def emit_array1(name, nums, comment=''):
    lines.append(f"  // {name}{(' ' + comment) if comment else ''}")
    lines.append(f"  {name}: array[0..{len(nums)-1}] of Tb64u64 = (")
    for i, n in enumerate(nums):
        u, _ = to_u64(n)
        sep = ',' if i < len(nums)-1 else ''
        lines.append(f"    (u:{fu(u)}){sep}  // {n}")
    lines.append("  );")
    lines.append("")

def emit_array2(name, rows, dim_comment=''):
    R = len(rows); C = len(rows[0])
    lines.append(f"  // {name}{(' ' + dim_comment) if dim_comment else ''}")
    lines.append(f"  {name}: array[0..{R-1},0..{C-1}] of Tb64u64 = (")
    for i, row in enumerate(rows):
        ents = [f"(u:{fu(to_u64(n)[0])})" for n in row]
        sep = ',' if i < R-1 else ''
        lines.append(f"    ({', '.join(ents)}){sep}  // i={i}")
    lines.append("  );")
    lines.append("")

def emit_named_2d(prefix, rows, comment=''):
    if comment:
        lines.append(f"  // {prefix}_<i>_<j>{(' ' + comment) if comment else ''}")
    for i, row in enumerate(rows):
        for j, n in enumerate(row):
            u, _ = to_u64(n)
            lines.append(f"  {prefix}_{i}_{j}: Tb64u64 = (u:{fu(u)});  // {n}")
    lines.append("")

emit_array2('cErfcT',     T,        '[6][13] asympt-fast polynomials (degree 23, odd coeffs)')
emit_array2('cErfcTacc',  Tacc,     '[10][30] asympt-accurate polynomials (zero-padded)')
emit_array1('cErfcE2',    E2_nums,  '(degree-19 exp_accurate poly, 8 dd + 12 single)')
# Phase 6.6 Pillar B: exception tables become literal-indexed after Pillar A unroll.
emit_named_2d('cErfcAsymptEx',  ex_asympt, '(22 asympt-accurate exception triples)')
emit_named_2d('cErfcAccNegEx',  ex_neg,    '(17 cr_erfc_accurate negative-x exception triples)')
emit_named_2d('cErfcAccPosEx',  ex_pos,    '(29 cr_erfc_accurate positive-x exception triples)')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"wrote {OUT}")
