#!/usr/bin/env python3
"""Generate src/erfc_const.inc by extracting tables from core-math erfc.c.

Tables extracted:
- T[6][13]            : asympt fast-path polynomials (cErfcT)
- Tacc[10][30]        : asympt accurate-path polynomials (cErfcTacc, padded to 30 cols)
- E2[28]              : degree-19 accurate exp polynomial (cErfcE2)
- exceptions in erfc_asympt_accurate (22 triples) (cErfcAsymptEx)
- exceptions in cr_erfc_accurate negative branch (17 triples) (cErfcAccNegEx)
- exceptions in cr_erfc_accurate positive branch (29 triples) (cErfcAccPosEx)

All hex floats are decoded with float.fromhex() and re-encoded as Tb64u64
records via struct.pack to avoid hand-typing bit patterns.
"""
import re, struct, os

SRC = os.path.join(os.path.dirname(__file__), '..', '..', 'core-math', 'src',
                   'binary64', 'erfc', 'erfc.c')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'erfc_const.inc')

with open(SRC) as f:
    text = f.read()

HEX = re.compile(r'-?0x[0-9a-fA-F.]+p[+-]?\d+')

def to_u64(s):
    v = float.fromhex(s)
    b = struct.pack('<d', v)
    return struct.unpack('<Q', b)[0], v

# ---- T[6][13] (in erfc.c, NOT erf.c) ----
m = re.search(r'static const double T\[6\]\[13\] = \{(.*?)\n\};', text, re.S)
assert m, 'T'
T_rows = re.findall(r'\{([^{}]*)\}', m.group(1))
assert len(T_rows) == 6
T = []
for row in T_rows:
    nums = HEX.findall(row)
    assert len(nums) == 13
    T.append(nums)

# ---- Tacc[10][30] (variable-degree polynomials, shorter rows zero-padded) ----
m = re.search(r'static const double Tacc\[10\]\[30\] = \{(.*?)\n\};', text, re.S)
assert m, 'Tacc'
Tacc_rows = re.findall(r'\{([^{}]*)\}', m.group(1))
assert len(Tacc_rows) == 10
Tacc = []
for row in Tacc_rows:
    nums = HEX.findall(row)
    # pad to 30 with literal "0x0p+0"
    while len(nums) < 30:
        nums.append('0x0p+0')
    Tacc.append(nums)

# ---- E2[] degree-19 exp accurate polynomial (8 dd + 12 single = 28 entries) ----
m = re.search(r'static const double E2\[\] = \{(.*?)\n\};', text, re.S)
assert m, 'E2'
E2_nums = HEX.findall(m.group(1))
assert len(E2_nums) == 28, len(E2_nums)

# ---- exception tables ----
def extract_after(marker_func_name, count, dim=3):
    idx = text.index(marker_func_name)
    sub = text[idx:]
    m = re.search(r'static const double exceptions\[(?:\d*)?\]\[3\] = \{(.*?)\n\s*\}\s*;', sub, re.S)
    assert m, marker_func_name
    rows = re.findall(r'\{([^{}]+)\}', m.group(1))
    assert len(rows) == count, (marker_func_name, len(rows), count)
    out = []
    for r in rows:
        nums = HEX.findall(r)
        assert len(nums) == dim
        out.append(nums)
    return out

# erfc_asympt_accurate has 22-entry exceptions table
ex_asympt = extract_after('erfc_asympt_accurate', 22)

# cr_erfc_accurate first occurrence (after definition); look for two exceptions blocks
cra_idx = text.index('cr_erfc_accurate (double x)')
sub = text[cra_idx:]
# negative-branch exceptions: 17 entries
m1 = re.search(r'static const double exceptions\[\]\[3\] = \{(.*?)\n\s*\}\s*;', sub, re.S)
assert m1
rows = re.findall(r'\{([^{}]+)\}', m1.group(1))
assert len(rows) == 17, len(rows)
ex_neg = []
for r in rows:
    nums = HEX.findall(r)
    assert len(nums) == 3
    ex_neg.append(nums)

# positive-branch exceptions: 29 entries (after first block)
sub2 = sub[m1.end():]
m2 = re.search(r'static const double exceptions\[\]\[3\] = \{(.*?)\n\s*\}\s*;', sub2, re.S)
assert m2
rows = re.findall(r'\{([^{}]+)\}', m2.group(1))
assert len(rows) == 29, len(rows)
ex_pos = []
for r in rows:
    nums = HEX.findall(r)
    assert len(nums) == 3
    ex_pos.append(nums)

# ---- emit ----
lines = ["// Auto-generated by tools/erfc_gen.py — do not edit by hand.",
         "// Source: core-math/src/binary64/erfc/erfc.c", ""]

def emit_array1(name, nums, comment=''):
    lines.append(f"  // {name}{(' ' + comment) if comment else ''}")
    lines.append(f"  {name}: array[0..{len(nums)-1}] of Tb64u64 = (")
    for i, n in enumerate(nums):
        u, _ = to_u64(n)
        sep = ',' if i < len(nums)-1 else ''
        lines.append(f"    (u:${u:016X}){sep}  // {n}")
    lines.append("  );")
    lines.append("")

def emit_array2(name, rows, dim_comment=''):
    R = len(rows); C = len(rows[0])
    lines.append(f"  // {name}{(' ' + dim_comment) if dim_comment else ''}")
    lines.append(f"  {name}: array[0..{R-1},0..{C-1}] of Tb64u64 = (")
    for i, row in enumerate(rows):
        ents = []
        for n in row:
            u, _ = to_u64(n)
            ents.append(f"(u:${u:016X})")
        sep = ',' if i < R-1 else ''
        lines.append(f"    ({', '.join(ents)}){sep}  // i={i}")
    lines.append("  );")
    lines.append("")

emit_array2('cErfcT',     T,        '[6][13] asympt-fast polynomials (degree 23, odd coeffs)')
emit_array2('cErfcTacc',  Tacc,     '[10][30] asympt-accurate polynomials (zero-padded)')
emit_array1('cErfcE2',    E2_nums,  '(degree-19 exp_accurate poly, 8 dd + 12 single)')
emit_array2('cErfcAsymptEx',  ex_asympt, '[22][3] asympt-accurate exception triples')
emit_array2('cErfcAccNegEx',  ex_neg,    '[17][3] cr_erfc_accurate negative-x exception triples')
emit_array2('cErfcAccPosEx',  ex_pos,    '[29][3] cr_erfc_accurate positive-x exception triples')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"wrote {OUT}")
