#!/usr/bin/env python3
"""Generate src/exp10m1_const.inc by extracting tables from core-math exp10m1.c.

Tables extracted:
- P[14] (fast polynomial degree-11, dd at degrees 1, 2, 3)
- Q[25] (accurate polynomial degree-17, dd at degrees 1..8)
- exceptions in cr_exp10m1 very-tiny path (74 triples)
- exceptions in exp10m1_accurate_tiny (145 triples)
- exceptions in exp10m1_accurate (81 triples)

T1/T2/Q_1/Q_2 are byte-identical to cExpT0/cExpT1/cExp2m1Q1/cExp2m1Q2 (exp2m1
already validated this), so we reuse those — NOT regenerated here.
"""
import re, struct, os

SRC = os.path.join(os.path.dirname(__file__), '..', '..', 'core-math', 'src',
                   'binary64', 'exp10m1', 'exp10m1.c')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'exp10m1_const.inc')

with open(SRC) as f:
    text = f.read()

HEX = re.compile(r'-?0x[0-9a-fA-F.]+p[+-]?\d+')

def to_u64(s):
    v = float.fromhex(s)
    return struct.unpack('<Q', struct.pack('<d', v))[0]

def extract_named_array(name, count):
    m = re.search(rf'static const double {name}\[\] = \{{(.*?)\n\s*\}};', text, re.S)
    assert m, name
    nums = HEX.findall(m.group(1))
    assert len(nums) == count, (name, len(nums), count)
    return nums

def extract_exception_block(after_marker, count):
    idx = text.index(after_marker)
    sub = text[idx:]
    m = re.search(r'static const double exceptions\[\w*\]\[3\] = \{(.*?)\n\s*\}\s*;',
                  sub, re.S)
    assert m, after_marker
    body = m.group(1)
    rows = re.findall(r'\{([^{}]+)\}', body)
    assert len(rows) == count, (after_marker, len(rows), count)
    out = []
    for r in rows:
        nums = HEX.findall(r)
        assert len(nums) == 3
        out.append(nums)
    return out

P = extract_named_array('P', 14)
Q = extract_named_array('Q', 25)

# very-tiny exceptions (74 triples, in 2^-104 < |x| <= 2^-54 branch of cr_exp10m1)
ex_verytiny = extract_exception_block('// 2^-104 < |x| <= 2^-54', 74)
# accurate-tiny exceptions (145)
ex_acctiny = extract_exception_block('exp10m1_accurate_tiny', 145)
# accurate exceptions (81), in exp10m1_accurate
ex_acc = extract_exception_block('static double exp10m1_accurate ', 81)

lines = ["// Auto-generated by tools/exp10m1_gen.py — do not edit by hand.",
         "// Source: core-math/src/binary64/exp10m1/exp10m1.c", ""]

def emit_array1(name, nums, comment=''):
    lines.append(f"  // {name} {comment}".rstrip())
    lines.append(f"  {name}: array[0..{len(nums)-1}] of Tb64u64 = (")
    for i, n in enumerate(nums):
        u = to_u64(n)
        sep = ',' if i < len(nums)-1 else ''
        lines.append(f"    (u:${u:016X}){sep}  // {n}")
    lines.append("  );")
    lines.append("")

def emit_array2_3(name, rows, comment=''):
    R = len(rows)
    lines.append(f"  // {name} {comment}".rstrip())
    lines.append(f"  {name}: array[0..{R-1},0..2] of Tb64u64 = (")
    for i, row in enumerate(rows):
        ents = [f"(u:${to_u64(n):016X})" for n in row]
        sep = ',' if i < R-1 else ''
        lines.append(f"    ({', '.join(ents)}){sep}  // {row[0]}")
    lines.append("  );")
    lines.append("")

emit_array1('cExp10m1P', P, '(fast polynomial degree-11, dd at degrees 1,2,3)')
emit_array1('cExp10m1Q', Q, '(accurate polynomial degree-17, dd at degrees 1..8)')
emit_array2_3('cExp10m1ExVTiny',  ex_verytiny, '(very-tiny exceptions, 74)')
emit_array2_3('cExp10m1ExAccTiny', ex_acctiny, '(accurate-tiny exceptions, 145)')
emit_array2_3('cExp10m1ExAcc',     ex_acc,     '(accurate exceptions, 81)')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"wrote {OUT}")
