#!/usr/bin/env python3
"""Generate src/exp2m1_const.inc by extracting tables from core-math exp2m1.c.

Tables extracted:
- Q_1[5], Q_2[9], P[12], Q[22] (polynomial coefficients)
- exceptions for cr_exp2m1 very-small path (56 triples)
- exceptions for exp2m1_accurate_tiny (59 triples)
- exceptions for exp2m1_accurate (93 triples)

T1[64][2] and T2[64][2] are byte-identical to pascoremath64.cExpT0/cExpT1
(verified manually) — NOT regenerated here, the port reuses them.
"""
import re, struct, os

SRC = os.path.join(os.path.dirname(__file__), '..', '..', 'core-math', 'src',
                   'binary64', 'exp2m1', 'exp2m1.c')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'exp2m1_const.inc')

with open(SRC) as f:
    text = f.read()

HEX = re.compile(r'-?0x[0-9a-fA-F.]+p[+-]?\d+')

def to_u64(s):
    v = float.fromhex(s)
    return struct.unpack('<Q', struct.pack('<d', v))[0]

def extract_named_array(name, count):
    m = re.search(rf'static const double {name}\[\] = \{{(.*?)\n\s*\}};', text, re.S)
    assert m, name
    nums = HEX.findall(m.group(1))
    assert len(nums) == count, (name, len(nums), count)
    return nums

def extract_exception_block(after_marker, count):
    idx = text.index(after_marker)
    sub = text[idx:]
    m = re.search(r'static const double exceptions\[\w*\]\[3\] = \{(.*?)\n\s*\}\s*;',
                  sub, re.S)
    assert m, after_marker
    body = m.group(1)
    rows = re.findall(r'\{([^{}]+)\}', body)
    assert len(rows) == count, (after_marker, len(rows), count)
    out = []
    for r in rows:
        nums = HEX.findall(r)
        assert len(nums) == 3
        out.append(nums)
    return out

Q1 = extract_named_array('Q_1', 5)
Q2 = extract_named_array('Q_2', 9)
P = extract_named_array('P', 12)
Q = extract_named_array('Q', 22)

# exceptions in cr_exp2m1 (very-tiny path, 56)
ex_verytiny = extract_exception_block('// 2^-104 < |x| <= 0x1.0527dbd87e24dp-51', 56)
# exceptions in exp2m1_accurate_tiny (59)
ex_acctiny = extract_exception_block('exp2m1_accurate_tiny', 59)
# exceptions in exp2m1_accurate (93)
ex_acc = extract_exception_block('static double exp2m1_accurate ', 93)

lines = ["// Auto-generated by tools/exp2m1_gen.py — do not edit by hand.",
         "// Source: core-math/src/binary64/exp2m1/exp2m1.c", ""]

def emit_array1(name, nums, comment=''):
    lines.append(f"  // {name} {comment}".rstrip())
    lines.append(f"  {name}: array[0..{len(nums)-1}] of Tb64u64 = (")
    for i, n in enumerate(nums):
        u = to_u64(n)
        sep = ',' if i < len(nums)-1 else ''
        lines.append(f"    (u:${u:016X}){sep}  // {n}")
    lines.append("  );")
    lines.append("")

def emit_array2_3(name, rows, comment=''):
    R = len(rows)
    lines.append(f"  // {name} {comment}".rstrip())
    lines.append(f"  {name}: array[0..{R-1},0..2] of Tb64u64 = (")
    for i, row in enumerate(rows):
        ents = [f"(u:${to_u64(n):016X})" for n in row]
        sep = ',' if i < R-1 else ''
        lines.append(f"    ({', '.join(ents)}){sep}  // {row[0]}")
    lines.append("  );")
    lines.append("")

emit_array1('cExp2m1Q1', Q1, '(fast q_1 degree-4)')
emit_array1('cExp2m1Q2', Q2, '(accurate q_2 with dd at idx 3,4)')
emit_array1('cExp2m1P',  P,  '(fast tiny polynomial degree-10, dd at idx 0,1 and 2,3)')
emit_array1('cExp2m1Q',  Q,  '(accurate tiny polynomial degree-15, dd at idx 0..13)')
emit_array2_3('cExp2m1ExVTiny',  ex_verytiny, '(very-tiny exceptions, 56)')
emit_array2_3('cExp2m1ExAccTiny', ex_acctiny, '(accurate-tiny exceptions, 59)')
emit_array2_3('cExp2m1ExAcc',     ex_acc,     '(accurate exceptions, 93)')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"wrote {OUT}")
