#!/usr/bin/env python3
"""Generate src/lgamma_const.inc by extracting tables from core-math lgamma.c.

Tables extracted (everything in lgamma.c that isn't inline scalar literals):
  cr_lgamma:
    - ubrd[20] (UInt32 thresholds)
    - offs[19] (region offsets)
    - cl[19][8] (low polynomial coefficients)
    - ch[19][5][2] (high polynomial dd-pair coefficients; C declares [13][2] but
      only 5 dd pairs filled per region)
    - tiny-c0[4][2] and tiny-q[8] (|x|<0.03125 small-x polynomial)
    - asym-c[2][2] and asym-q[5] (|x|>=8.29541 asymptotic)

  as_logd / as_logd_accurate:
    - B[32] (struct {ushort c0; short c1}) — used by both
    - r1[33], r2[33]
    - l1[33][2], l2[33][2] (as_logd)
    - h1[33][3], h2[33][3] (as_logd_accurate)
    - logd_c[4]            (as_logd polynomial)
    - logda_c[9][2]        (as_logd_accurate polynomial)

  stpi[65][2] (sin/cos at i*pi/128)

  as_sinpipid:
    - sinp_c[4], sinp_s[4], sinp_c0, sinp_s0  (kx<2 + main path)
    - sinp_kx2_c[2], sinp_kx2_cl[3]           (kx<2 small-z polynomial)

  as_sinpipid_accurate:
    - sinpa_c[5][2], sinpa_s[6][2]

  as_lgamma_asym_accurate:
    - asym48_c[8][2]   (xh>=48)
    - asym14_c[12][2]  (xh>=14.5)
    - asym4_c[28][2]   (xh<14.5)

  as_lgamma_database: db[19][3]

  as_lgamma_accurate:
    - acc_c0[34][2]    (lgamma(x)+ln|x|)/x for x in [-0.25,0.25]
    - acc_b[30][2]     (lgamma(1.5+x))
    - 14 polynomial branches near negative half/quarter integers, each:
        x0[3] doubles, c[N][2] dd-pairs, plus the polyd cutoff k

The Python generator decodes every hex float with float.fromhex() and re-encodes
via struct.pack('<d', v) -> Tb64u64 records, eliminating any risk of hand-typed
bit-pack typos (lesson reinforced from acosh, log1p, erf, exp2m1, acospi,
exp10m1, tgamma).
"""
import re, struct, os

SRC = os.path.join(os.path.dirname(__file__), '..', '..', 'core-math', 'src',
                   'binary64', 'lgamma', 'lgamma.c')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'lgamma_const.inc')

with open(SRC) as f:
    text = f.read()

HEX = re.compile(r'-?0x[0-9a-fA-F.]+p[+-]?\d+')

def to_u64(s):
    v = float.fromhex(s)
    b = struct.pack('<d', v)
    return struct.unpack('<Q', b)[0], v

def get_block(start_marker, end_marker, where=None):
    """Return text between markers (start_marker exclusive, end_marker exclusive),
    optionally restricted to substring after `where`."""
    body = text
    if where is not None:
        body = body[text.index(where):]
    a = body.index(start_marker) + len(start_marker)
    b = body.index(end_marker, a)
    return body[a:b]

def parse_dd_rows(body, expected_rows=None):
    """Parse {{a,b},{c,d},...} into list of [a,b] hex strings."""
    rows = re.findall(r'\{([^{}]+)\}', body)
    out = []
    for r in rows:
        nums = HEX.findall(r)
        if len(nums) == 2:
            out.append(nums)
    if expected_rows is not None:
        assert len(out) == expected_rows, (expected_rows, len(out))
    return out

def parse_flat(body):
    return HEX.findall(body)

lines = ["// Auto-generated by tools/lgamma_gen.py — do not edit by hand.",
         "// Source: core-math/src/binary64/lgamma/lgamma.c", ""]

def emit_array1(name, nums, comment=''):
    lines.append(f"  // {name}{(' ' + comment) if comment else ''}")
    lines.append(f"  {name}: array[0..{len(nums)-1}] of Tb64u64 = (")
    for i, n in enumerate(nums):
        u, v = to_u64(n)
        sep = ',' if i < len(nums)-1 else ''
        lines.append(f"    (u:${u:016X}){sep}  // {n}")
    lines.append("  );")
    lines.append("")

def emit_array2(name, rows, dim_comment=''):
    R = len(rows); C = len(rows[0])
    lines.append(f"  // {name}{(' ' + dim_comment) if dim_comment else ''}")
    lines.append(f"  {name}: array[0..{R-1},0..{C-1}] of Tb64u64 = (")
    for i, row in enumerate(rows):
        ents = []
        for n in row:
            u, _ = to_u64(n)
            ents.append(f"(u:${u:016X})")
        sep = ',' if i < R-1 else ''
        lines.append(f"    ({', '.join(ents)}){sep}  // i={i}")
    lines.append("  );")
    lines.append("")

def emit_array3(name, rows, dim_comment=''):
    R = len(rows); P = len(rows[0]); C = len(rows[0][0])
    lines.append(f"  // {name}{(' ' + dim_comment) if dim_comment else ''}")
    lines.append(f"  {name}: array[0..{R-1},0..{P-1},0..{C-1}] of Tb64u64 = (")
    for i, row in enumerate(rows):
        pairs = []
        for pair in row:
            ents = ', '.join(f"(u:${to_u64(n)[0]:016X})" for n in pair)
            pairs.append(f"({ents})")
        sep = ',' if i < R-1 else ''
        lines.append(f"    ({', '.join(pairs)}){sep}  // i={i}")
    lines.append("  );")
    lines.append("")

# ---- cr_lgamma: ubrd, offs, cl, ch ----
fn_lgamma = text.index('double cr_lgamma(double x)')
fn_lgamma_end = text.index('double as_logd(double x', fn_lgamma)

# ubrd[20]: 20 hex literals like 0x1ff0000
m = re.search(r'static const unsigned ubrd\[20\] = \{([^}]+)\}', text[fn_lgamma:fn_lgamma_end])
ubrd_vals = [int(s, 16) for s in re.findall(r'0x[0-9a-fA-F]+', m.group(1))]
assert len(ubrd_vals) == 20
lines.append('  // cLgammaUbrd: range borders (UInt32)')
lines.append('  cLgammaUbrd: array[0..19] of UInt32 = (')
for i, v in enumerate(ubrd_vals):
    sep = ',' if i < 19 else ''
    lines.append(f'    ${v:08X}{sep}')
lines.append('  );')
lines.append('')

# offs[19]
m = re.search(r'static const double offs\[19\] = \{([^}]+)\}', text[fn_lgamma:fn_lgamma_end])
offs_nums = HEX.findall(m.group(1))
emit_array1('cLgammaOffs', offs_nums, '(region offsets)')

# cl[19][8]
m = re.search(r'static const double cl\[19\]\[8\] = \{(.*?)\n  \};', text[fn_lgamma:fn_lgamma_end], re.S)
cl_body = m.group(1)
cl_rows = re.findall(r'\{([^{}]+)\}', cl_body)
assert len(cl_rows) == 19, len(cl_rows)
cl_arr = []
for r in cl_rows:
    nums = HEX.findall(r)
    assert len(nums) == 8
    cl_arr.append(nums)
emit_array2('cLgammaCL', cl_arr, '[19][8] low-poly coefficients per region')

# ch[19][13][2] — only 5 dd-pairs filled per row; build [19][5][2]
m = re.search(r'static const double ch\[19\]\[13\]\[2\] = \{(.*?)\n  \};', text[fn_lgamma:fn_lgamma_end], re.S)
ch_body = m.group(1)
# split into 19 outer rows by matching balanced braces of two-deep
# easier: find all 'inner' {a,b} pairs, group by 5
inner = re.findall(r'\{([^{}]+)\}', ch_body)
assert len(inner) == 19*5, len(inner)
ch_rows = []
for i in range(19):
    pairs = []
    for j in range(5):
        nums = HEX.findall(inner[i*5+j])
        assert len(nums) == 2
        pairs.append(nums)
    ch_rows.append(pairs)
emit_array3('cLgammaCH', ch_rows, '[19][5][2] high dd-pair coefficients per region')

# Tiny |x|<0.03125 polynomial
# c0[][2] (4 entries) and q[] (8 entries) — they appear inside the |x|<0.5 branch
tiny_block = re.search(r'\} else if\(au<0x1fd0000\)\{[^}]*?static const double c0\[\]\[2\] = \{(.*?)\};\s*static const double q\[\] = \{(.*?)\};', text[fn_lgamma:fn_lgamma_end], re.S)
assert tiny_block
tiny_c0 = parse_dd_rows(tiny_block.group(1), expected_rows=4)
tiny_q = HEX.findall(tiny_block.group(2))
assert len(tiny_q) == 8
emit_array2('cLgammaTinyC0', tiny_c0, '[4][2] tiny |x|<0.03125 dd polynomial')
emit_array1('cLgammaTinyQ', tiny_q, '[8] tiny |x|<0.03125 single polynomial')

# Asymptotic |x|>=8.29541 polynomial
# c[][2] (2 entries) and q[] (5 entries)
asym_block = re.search(r'if\(au>=ubrd\[19\]\).*?static const double c\[\]\[2\] = \{(.*?)\};\s*static const double q\[\] = \{(.*?)\};', text[fn_lgamma:fn_lgamma_end], re.S)
assert asym_block
asym_c = parse_dd_rows(asym_block.group(1), expected_rows=2)
asym_q = HEX.findall(asym_block.group(2))
assert len(asym_q) == 5
emit_array2('cLgammaAsymC', asym_c, '[2][2] |x|>=8.29541 dd constants')
emit_array1('cLgammaAsymQ', asym_q, '[5] |x|>=8.29541 single polynomial')

# ---- as_logd: B[32] (struct), r1[33], r2[33], l1[33][2], l2[33][2], c[4] ----
fn_logd_a = text.index('double as_logd(double x, double *l)')
fn_logd_b = text.index('double as_logd_accurate(double x', fn_logd_a)

# B[32]: pairs of {c0, c1}
m = re.search(r'static const struct \{ushort c0; short c1;\} B\[\] = \{(.*?)\};', text[fn_logd_a:fn_logd_b], re.S)
B_pairs = re.findall(r'\{(\d+),\s*(-?\d+)\}', m.group(1))
assert len(B_pairs) == 32, len(B_pairs)
lines.append('  // cLgammaLogB: 32 pairs of (c0:UInt16; c1:Int16) used in as_logd reduction')
lines.append('  cLgammaLogB: array[0..31] of record c0: UInt16; c1: Int16; end = (')
for i, (a, b) in enumerate(B_pairs):
    sep = ',' if i < 31 else ''
    lines.append(f'    (c0:{a}; c1:{b}){sep}')
lines.append('  );')
lines.append('')

m = re.search(r'static const double r1\[\] =\s*\{(.*?)\};', text[fn_logd_a:fn_logd_b], re.S)
r1_nums = HEX.findall(m.group(1))
assert len(r1_nums) == 33
emit_array1('cLgammaLogR1', r1_nums, '[33]')

m = re.search(r'static const double r2\[\] =\s*\{(.*?)\};', text[fn_logd_a:fn_logd_b], re.S)
r2_nums = HEX.findall(m.group(1))
assert len(r2_nums) == 33
emit_array1('cLgammaLogR2', r2_nums, '[33]')

m = re.search(r'static const double l1\[\]\[2\] = \{(.*?)\};', text[fn_logd_a:fn_logd_b], re.S)
l1_rows = parse_dd_rows(m.group(1), expected_rows=33)
emit_array2('cLgammaLogL1', l1_rows, '[33][2]')

m = re.search(r'static const double l2\[\]\[2\] = \{(.*?)\};', text[fn_logd_a:fn_logd_b], re.S)
l2_rows = parse_dd_rows(m.group(1), expected_rows=32)
emit_array2('cLgammaLogL2', l2_rows, '[32][2]')

# c[4] polynomial
m = re.search(r'static const double c\[\] = \{(-?0x[^}]+?)\};', text[fn_logd_a:fn_logd_b])
logd_c = HEX.findall(m.group(1))
assert len(logd_c) == 4
emit_array1('cLgammaLogC', logd_c, '[4] as_logd polynomial')

# ---- as_logd_accurate ----
fn_logda_a = text.index('double as_logd_accurate(double x, double *l, double *l_)')
fn_logda_b = text.index('static const double stpi', fn_logda_a)

# h1[33][3], h2[33][3]
m = re.search(r'static const double h1\[\]\[3\] = \{(.*?)\n  \};', text[fn_logda_a:fn_logda_b], re.S)
h1_body = m.group(1)
h1_rows = []
for inner in re.findall(r'\{([^{}]+)\}', h1_body):
    nums = HEX.findall(inner)
    assert len(nums) == 3, (len(nums), inner)
    h1_rows.append(nums)
assert len(h1_rows) == 33, len(h1_rows)
emit_array2('cLgammaLogH1', h1_rows, '[33][3]')

m = re.search(r'static const double h2\[\]\[3\] = \{(.*?)\n  \};', text[fn_logda_a:fn_logda_b], re.S)
h2_body = m.group(1)
h2_rows = []
for inner in re.findall(r'\{([^{}]+)\}', h2_body):
    nums = HEX.findall(inner)
    assert len(nums) == 3
    h2_rows.append(nums)
assert len(h2_rows) == 33
emit_array2('cLgammaLogH2', h2_rows, '[33][3]')

# c[][2] degree-9 (9 dd-pairs)
m = re.search(r'static const double c\[\]\[2\] = \{(.*?)\};', text[fn_logda_a:fn_logda_b], re.S)
logda_c = parse_dd_rows(m.group(1), expected_rows=9)
emit_array2('cLgammaLogAC', logda_c, '[9][2] as_logd_accurate dd polynomial')

# ---- stpi[65][2] ----
m = re.search(r'static const double stpi\[\]\[2\] = \{(.*?)\};', text, re.S)
stpi_rows = parse_dd_rows(m.group(1), expected_rows=65)
emit_array2('cLgammaStpi', stpi_rows, '[65][2] sin/cos at i*pi/128')

# ---- as_sinpipid: kx<2 small + main path ----
fn_sin_a = text.index('double as_sinpipid(double x, double *l)')
fn_sin_b = text.index('double as_sinpipid_accurate(double x', fn_sin_a)

m = re.search(r'static const double c\[2\] = \{(.*?)\};', text[fn_sin_a:fn_sin_b])
sinp_kx2_c = HEX.findall(m.group(1))
assert len(sinp_kx2_c) == 2
emit_array1('cLgammaSinKx2C', sinp_kx2_c, '[2] kx<2 dd constants')

m = re.search(r'static const double cl\[\] = \{(.*?)\};', text[fn_sin_a:fn_sin_b])
sinp_kx2_cl = HEX.findall(m.group(1))
assert len(sinp_kx2_cl) == 3
emit_array1('cLgammaSinKx2Cl', sinp_kx2_cl, '[3] kx<2 polynomial')

# main: c[4], s[4], c0 scalar, s0 scalar
m_c = re.search(r'static const double c\[\] = \{(.*?)\};', text[fn_sin_a:fn_sin_b])
sinp_c = HEX.findall(m_c.group(1))
assert len(sinp_c) == 4
emit_array1('cLgammaSinC', sinp_c, '[4] sinpipid polynomial — cos coeffs')

m_s = re.search(r'static const double s\[\] = \{(.*?)\};', text[fn_sin_a:fn_sin_b])
sinp_s = HEX.findall(m_s.group(1))
assert len(sinp_s) == 4
emit_array1('cLgammaSinS', sinp_s, '[4] sinpipid polynomial — sin coeffs')

m_c0 = re.search(r'double c0 = (-?0x[^;]+);', text[fn_sin_a:fn_sin_b])
m_s0 = re.search(r'double s0 = (0x[^;]+);', text[fn_sin_a:fn_sin_b])
emit_array1('cLgammaSinC0', [m_c0.group(1)], '(scalar)')
emit_array1('cLgammaSinS0', [m_s0.group(1)], '(scalar)')

# ---- as_sinpipid_accurate ----
fn_sina_a = text.index('double as_sinpipid_accurate(double x')
fn_sina_b = text.index('double as_lgamma_asym_accurate(', fn_sina_a)

m = re.search(r'static const double c\[\]\[2\] = \{(.*?)\};', text[fn_sina_a:fn_sina_b], re.S)
sinpa_c = parse_dd_rows(m.group(1), expected_rows=5)
emit_array2('cLgammaSinAccC', sinpa_c, '[5][2]')

m = re.search(r'static const double s\[\]\[2\] = \{(.*?)\};', text[fn_sina_a:fn_sina_b], re.S)
sinpa_s = parse_dd_rows(m.group(1), expected_rows=6)
emit_array2('cLgammaSinAccS', sinpa_s, '[6][2]')

# ---- as_lgamma_asym_accurate (3 branches) ----
fn_asy_a = text.index('double as_lgamma_asym_accurate(')
# Find end at start of next definition (none after; use end of file)
fn_asy_b = len(text)

# xh>=48: c[8][2]
asy_block48 = re.search(r'if\(xh>=48\)\{.*?static const double c\[\]\[2\] = \{(.*?)\};', text[fn_asy_a:fn_asy_b], re.S)
asy48_c = parse_dd_rows(asy_block48.group(1), expected_rows=8)
emit_array2('cLgammaAsy48C', asy48_c, '[8][2] xh>=48 polynomial')

# xh>=14.5: c[12][2]
asy_block14 = re.search(r'else if\(xh>=14\.5\)\{.*?static const double c\[\]\[2\] = \{(.*?)\};', text[fn_asy_a:fn_asy_b], re.S)
asy14_c = parse_dd_rows(asy_block14.group(1), expected_rows=12)
emit_array2('cLgammaAsy14C', asy14_c, '[12][2] xh>=14.5 polynomial')

# else (xh<14.5): c[28][2]
asy_block4 = re.search(r'\} else \{\s*static const double c\[\]\[2\] = \{(.*?)\};', text[fn_asy_a:fn_asy_b], re.S)
asy4_c = parse_dd_rows(asy_block4.group(1), expected_rows=28)
emit_array2('cLgammaAsy4C', asy4_c, '[28][2] xh<14.5 polynomial')

# ---- as_lgamma_database: db[19][3] ----
fn_db_a = text.index('static __attribute__((noinline)) double as_lgamma_database')
fn_db_b = text.index('static __attribute__((noinline)) double as_lgamma_accurate', fn_db_a)
m = re.search(r'static const double db\[\]\[3\] = \{(.*?)\};', text[fn_db_a:fn_db_b], re.S)
db_body = m.group(1)
db_rows = []
for inner in re.findall(r'\{([^{}]+)\}', db_body):
    nums = HEX.findall(inner)
    assert len(nums) == 3
    db_rows.append(nums)
assert len(db_rows) == 19, len(db_rows)
emit_array2('cLgammaDB', db_rows, '[19][3] database for ~zero outputs')

# ---- as_lgamma_accurate: c0[34][2], b[30][2] + 14 polynomial branches ----
fn_acc_a = text.index('static __attribute__((noinline)) double as_lgamma_accurate(double x)')
fn_acc_b = text.index('double cr_lgamma(double x)', fn_acc_a)

m = re.search(r'static const double c0\[\]\[2\] = \{(.*?)\};', text[fn_acc_a:fn_acc_b], re.S)
acc_c0 = parse_dd_rows(m.group(1), expected_rows=34)
emit_array2('cLgammaAccC0', acc_c0, '[34][2] near-zero polynomial')

m = re.search(r'static const double b\[\]\[2\] = \{(.*?)\};', text[fn_acc_a:fn_acc_b], re.S)
acc_b = parse_dd_rows(m.group(1), expected_rows=30)
emit_array2('cLgammaAccB', acc_b, '[30][2] near-1.5 polynomial')

# Now extract the 14 polynomial branches near negative half/quarter integers.
# Each appears as `static const double x0[] = {...}; static const double c[][2] = {...};`
# under a unique branch-condition. We extract them in document order, each producing
# x0[3] and c[N][2] tables, plus the polyd cutoff k from `int n = ..., k = K;`
acc_body = text[fn_acc_a:fn_acc_b]
# Locate each "static const double x0[]" inside as_lgamma_accurate
x0_iter = list(re.finditer(r'static const double x0\[\] = \{(.*?)\};', acc_body, re.S))
assert len(x0_iter) >= 8, len(x0_iter)

branch_meta = []
for idx, mm in enumerate(x0_iter):
    x0_nums = HEX.findall(mm.group(1))
    assert len(x0_nums) == 3, (idx, len(x0_nums))
    # find following c[][2] within next ~6KB
    after = acc_body[mm.end(): mm.end()+8000]
    cc = re.search(r'static const double c\[\]\[2\] = \{(.*?)\};', after, re.S)
    assert cc, idx
    c_rows = parse_dd_rows(cc.group(1))
    # find the polyd-cutoff k
    rest = after[cc.end():]
    km = re.search(r'int n = sizeof\(c\)/sizeof\(c\[0\]\), k = (\d+);', rest)
    assert km, idx
    k = int(km.group(1))
    # find sc constant
    sm = re.search(r'const double sc = (0x[^;]+);', rest)
    assert sm, idx
    sc_str = sm.group(1)
    branch_meta.append((idx, x0_nums, c_rows, k, sc_str))

# Emit as Lgamma.AccBr<i>X0 / Lgamma.AccBr<i>C / scalars Lgamma.AccBr<i>Sc
lines.append(f'  // cLgammaAccNumBranches: number of accurate-path polynomial branches')
lines.append(f'  cLgammaAccNumBranches = {len(branch_meta)};')
lines.append('')

for (idx, x0_nums, c_rows, k, sc_str) in branch_meta:
    emit_array1(f'cLgammaAccBr{idx}X0', x0_nums, f'(branch {idx})')
    emit_array2(f'cLgammaAccBr{idx}C', c_rows, f'(branch {idx})')
    u, v = to_u64(sc_str)
    lines.append(f'  cLgammaAccBr{idx}Sc: Tb64u64 = (u:${u:016X}); // {sc_str}')
    lines.append(f'  cLgammaAccBr{idx}K = {k};')
    lines.append(f'  cLgammaAccBr{idx}N = {len(c_rows)};')
    lines.append('')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"wrote {OUT}: {sum(1 for _ in open(OUT))} lines, {len(branch_meta)} accurate branches")
