#!/usr/bin/env python3
"""Generate src/log10p1_const.inc from core-math/src/binary64/log10p1/log10p1.c.

Emits the log10p1-specific tables: P[7] (degree-7 fast poly), Pa[11]
(degree-11 medium poly), Pacc (degree-17 accurate-tiny poly, mixed dd/single
representation), exceptions[222][2] / exceptions_rnd[222], plus the
T/U exact-result tables for x=10^n-1.

The dint tables (_INVERSE_2, _LOG_INV_2, P_2, LOG2, M_ONE) are byte-identical
to log.c — reuse via log_const.inc.  LOG10_INV is identical to log10's
cLog10OneOverLog10Dint.
"""
import re, struct, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'log10p1', 'log10p1.c')
OUT = os.path.join(ROOT, 'src', 'log10p1_const.inc')

def b64(s):
    f = float.fromhex(s)
    return struct.unpack('<Q', struct.pack('<d', f))[0]

def fu(u):
    return f"$%016X" % u

def slurp(p):
    with open(p) as f:
        return f.read()

src = slurp(SRC)

def slice_array(text, name):
    m = re.search(rf'\b{re.escape(name)}\s*(?:\[[^\]]*\]\s*)+=\s*\{{', text)
    assert m, name
    i = m.end() - 1
    depth = 0
    j = i
    while j < len(text):
        if text[j] == '{':
            depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0:
                return text[i:j+1]
        j += 1
    raise SystemExit('mismatched braces for ' + name)

# P[7]
p_block = slice_array(src, 'P')
pvals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', p_block)
assert len(pvals) == 7, len(pvals)
P = [b64(v) for v in pvals]

# Pa[11]
pa_block = slice_array(src, 'Pa')
pavals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', pa_block)
assert len(pavals) == 11, len(pavals)
Pa = [b64(v) for v in pavals]

# Pacc[]: 25 doubles (mixed dd/single — flat list)
pacc_block = slice_array(src, 'Pacc')
paccvals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', pacc_block)
assert len(paccvals) == 25, len(paccvals)
Pacc = [b64(v) for v in paccvals]

# exceptions[EXCEPTIONS][2]
ex_block = slice_array(src, 'exceptions')
# Each entry is {hex, hex}
pairs = re.findall(r'\{([^{}]+)\}', ex_block)
assert len(pairs) == 222, len(pairs)
EXC = []
for p in pairs:
    nums = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', p)
    assert len(nums) == 2
    EXC.append((b64(nums[0]), b64(nums[1])))

# exceptions_rnd[EXCEPTIONS]
exr_block = slice_array(src, 'exceptions_rnd')
# Strip C comments first to avoid catching numeric literals inside them.
exr_clean = re.sub(r'/\*.*?\*/', ' ', exr_block, flags=re.DOTALL)
exr_clean = re.sub(r'//[^\n]*', ' ', exr_clean)
exr_vals = re.findall(r'-?\d+', exr_clean)
assert len(exr_vals) == 222, len(exr_vals)
EXR = [int(v) for v in exr_vals]

# T_acc[13][3] — accurate-path exceptions (the first T encountered)
t_block = slice_array(src, 'T')
tvals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', t_block)
assert len(tvals) == 39, len(tvals)
T_ACC = [(b64(tvals[3*i]), b64(tvals[3*i+1]), b64(tvals[3*i+2])) for i in range(13)]

# T_int[50], U_int[50] — exact x=10^n-1 fast detection (the second T/U pair).
# Find the SECOND `T[] = {` then the matching U.
matches = list(re.finditer(r'\bT\s*\[\s*\]\s*=\s*\{', src))
assert len(matches) >= 1
# Use the last occurrence (the integer fast-path table)
m = matches[-1]
i = m.end() - 1
depth = 0
j = i
while j < len(src):
    if src[j] == '{': depth += 1
    elif src[j] == '}':
        depth -= 1
        if depth == 0: break
    j += 1
t_int_block = src[i:j+1]
tvals2 = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', t_int_block)
assert len(tvals2) == 50, len(tvals2)
T_INT = [b64(v) for v in tvals2]

# Find U after that point
u_match = re.search(r'\bU\s*\[\s*\]\s*=\s*\{', src[j+1:])
assert u_match
u_start = j + 1 + u_match.end() - 1
depth = 0; k = u_start
while k < len(src):
    if src[k] == '{': depth += 1
    elif src[k] == '}':
        depth -= 1
        if depth == 0: break
    k += 1
u_block = src[u_start:k+1]
u_clean = re.sub(r'/\*.*?\*/', ' ', u_block, flags=re.DOTALL)
uvals = re.findall(r'-?\d+', u_clean)
assert len(uvals) == 50, len(uvals)
U_TBL = [int(v) for v in uvals]
T_TBL = T_INT

# Constants
INVLOG10H = b64('0x1.bcb7b1526e50ep-2')
INVLOG10L = b64('0x1.95355baaafad3p-57')

# Lines
lines = []
lines.append('// AUTO-GENERATED by tools/log10p1_gen.py from core-math/src/binary64/log10p1/log10p1.c')
lines.append('// Do not hand-edit; rerun tools/log10p1_gen.py after upstream changes.')
lines.append('// Reuses cLogInverse / cLogInvH / cLogInvL / cLogInverse2 / cLogLogInv2 /')
lines.append('// cLogP2 / cLogLog2Dint / cLogMOneDint from log_const.inc and')
lines.append('// cLog10OneOverLog10Dint from log10_port.inc.')
lines.append('')

# Note: this file is included inside an existing `const` block in log10p1_port.inc.
def emit_arr(name, vals, group=4, comment=None):
    n = len(vals)
    lines.append(f'  {name}: array[0..{n-1}] of Tb64u64 = (')
    for i in range(0, n, group):
        chunk = vals[i:i+group]
        s = ', '.join(f'(u:{fu(u)})' for u in chunk)
        sep = ',' if i + group < n else ''
        lines.append(f'    {s}{sep}')
    lines.append('  );')
    lines.append('')

emit_arr('cLog10p1P', P, 4)
emit_arr('cLog10p1Pa', Pa, 4)
emit_arr('cLog10p1Pacc', Pacc, 4)

# exceptions[222][2] flattened as 444 entries: [k][0],[k][1] interleaved is the
# C layout, but for binary search by [k][0] we want two parallel arrays.
EXC_X = [e[0] for e in EXC]
EXC_H = [e[1] for e in EXC]
emit_arr('cLog10p1ExX', EXC_X, 4)
emit_arr('cLog10p1ExH', EXC_H, 4)

# exceptions_rnd as ShortInt array
n = len(EXR)
lines.append(f'  cLog10p1ExRnd: array[0..{n-1}] of ShortInt = (')
for i in range(0, n, 16):
    chunk = EXR[i:i+16]
    s = ', '.join(str(v) for v in chunk)
    sep = ',' if i + 16 < n else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')

# T[50], U[50]
# T_acc[13] flattened as 39 entries (x0,h,l triples).
TACC_FLAT = []
for (x, h, l) in T_ACC:
    TACC_FLAT.extend([x, h, l])
emit_arr('cLog10p1Tacc', TACC_FLAT, 3)
emit_arr('cLog10p1T', T_TBL, 4)
n = len(U_TBL)
lines.append(f'  cLog10p1U: array[0..{n-1}] of ShortInt = (')
for i in range(0, n, 16):
    chunk = U_TBL[i:i+16]
    s = ', '.join(str(v) for v in chunk)
    sep = ',' if i + 16 < n else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')

# INVLOG10H/L
lines.append(f'  cLog10p1InvLog10H: Tb64u64 = (u:{fu(INVLOG10H)}); // 0x1.bcb7b1526e50ep-2')
lines.append(f'  cLog10p1InvLog10L: Tb64u64 = (u:{fu(INVLOG10L)}); // 0x1.95355baaafad3p-57')
# err constants
lines.append(f'  cLog10p1ErrSmall: Tb64u64 = (u:{fu(b64("0x1.d4p-62"))}); // 0x1.d4p-62')
lines.append(f'  cLog10p1ErrMain:  Tb64u64 = (u:{fu(b64("0x1.0ap-68"))}); // 0x1.0ap-68')
lines.append('')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f'Wrote {OUT} ({len(lines)} lines)')
