#!/usr/bin/env python3
"""Generate src/log2p1_const.inc from core-math/src/binary64/log2p1/log2p1.c.

Emits the log2p1-specific tables: P[7] (degree-7 fast poly), Pa[11]
(degree-11 medium poly), Pacc[24] (degree-17 accurate-tiny poly, mixed dd/single
representation), exceptions[247][2] / exceptions_rnd[247], T[53] exact x=2^n-1
table, INVLOG2H/L constants, and LOG2_INV dint constant (for accurate path).

The dint tables (_INVERSE_2, _LOG_INV_2, P_2, LOG2, M_ONE) are byte-identical
to log.c — reuse via log_const.inc. _INVERSE/_LOG_INV are likewise reused.
"""
import re, struct, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'log2p1', 'log2p1.c')
OUT = os.path.join(ROOT, 'src', 'log2p1_const.inc')


def b64(s):
    f = float.fromhex(s)
    return struct.unpack('<Q', struct.pack('<d', f))[0]


def fu(u):
    return f"$%016X" % u


def slurp(p):
    with open(p) as f:
        return f.read()


src = slurp(SRC)


def slice_array(text, name, occurrence=0):
    matches = list(re.finditer(rf'\b{re.escape(name)}\s*(?:\[[^\]]*\]\s*)+=\s*\{{', text))
    assert matches, name
    m = matches[occurrence]
    i = m.end() - 1
    depth = 0
    j = i
    while j < len(text):
        if text[j] == '{':
            depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0:
                return text[i:j+1]
        j += 1
    raise SystemExit('mismatched braces for ' + name)


# P[7]
p_block = slice_array(src, 'P')
pvals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', p_block)
assert len(pvals) == 7, len(pvals)
P = [b64(v) for v in pvals]

# Pa[11]
pa_block = slice_array(src, 'Pa')
pavals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', pa_block)
assert len(pavals) == 11, len(pavals)
Pa = [b64(v) for v in pavals]

# Pacc[]: 24 doubles (mixed dd/single — flat list)
pacc_block = slice_array(src, 'Pacc')
paccvals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', pacc_block)
assert len(paccvals) == 24, len(paccvals)
Pacc = [b64(v) for v in paccvals]

# exceptions[EXCEPTIONS][2]
ex_block = slice_array(src, 'exceptions')
pairs = re.findall(r'\{([^{}]+)\}', ex_block)
assert len(pairs) == 247, len(pairs)
EXC = []
for p in pairs:
    nums = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', p)
    assert len(nums) == 2
    EXC.append((b64(nums[0]), b64(nums[1])))

# exceptions_rnd[EXCEPTIONS]
exr_block = slice_array(src, 'exceptions_rnd')
exr_clean = re.sub(r'/\*.*?\*/', ' ', exr_block, flags=re.DOTALL)
exr_clean = re.sub(r'//[^\n]*', ' ', exr_clean)
exr_vals = re.findall(r'-?\d+', exr_clean)
assert len(exr_vals) == 247, len(exr_vals)
EXR = [int(v) for v in exr_vals]

# T[53] — exact x=2^n-1 fast detection (the only T[] in log2p1.c).
t_block = slice_array(src, 'T')
tvals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', t_block)
assert len(tvals) == 53, len(tvals)
T_TBL = [b64(v) for v in tvals]

# Constants
INVLOG2H = b64('0x1.71547652b82fep+0')
INVLOG2L = b64('0x1.777d0ffda0d24p-56')

lines = []
lines.append('// AUTO-GENERATED by tools/log2p1_gen.py from core-math/src/binary64/log2p1/log2p1.c')
lines.append('// Do not hand-edit; rerun tools/log2p1_gen.py after upstream changes.')
lines.append('// Reuses cLogInverse / cLogInvH / cLogInvL / cLogInverse2 / cLogLogInv2 /')
lines.append('// cLogP2 / cLogLog2Dint / cLogMOneDint / cLogLog2h / cLogLog2l from')
lines.append('// log_const.inc. LOG2_INV dint (2^12/log(2)) is local to log2p1.')
lines.append('')


def emit_arr(name, vals, group=4):
    n = len(vals)
    lines.append(f'  {name}: array[0..{n-1}] of Tb64u64 = (')
    for i in range(0, n, group):
        chunk = vals[i:i+group]
        s = ', '.join(f'(u:{fu(u)})' for u in chunk)
        sep = ',' if i + group < n else ''
        lines.append(f'    {s}{sep}')
    lines.append('  );')
    lines.append('')


emit_arr('cLog2p1P', P, 4)
emit_arr('cLog2p1Pa', Pa, 4)
emit_arr('cLog2p1Pacc', Pacc, 4)

EXC_X = [e[0] for e in EXC]
EXC_H = [e[1] for e in EXC]
emit_arr('cLog2p1ExX', EXC_X, 4)
emit_arr('cLog2p1ExH', EXC_H, 4)

n = len(EXR)
lines.append(f'  cLog2p1ExRnd: array[0..{n-1}] of ShortInt = (')
for i in range(0, n, 16):
    chunk = EXR[i:i+16]
    s = ', '.join(str(v) for v in chunk)
    sep = ',' if i + 16 < n else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')

emit_arr('cLog2p1T', T_TBL, 4)

# INVLOG2H/L
lines.append(f'  cLog2p1InvLog2H: Tb64u64 = (u:{fu(INVLOG2H)}); // 0x1.71547652b82fep+0')
lines.append(f'  cLog2p1InvLog2L: Tb64u64 = (u:{fu(INVLOG2L)}); // 0x1.777d0ffda0d24p-56')

# err constants:
#  fast tiny path: 0x1.d4p-62  (relative err)
#  fast main path: 0x1.23p-68  (relative err)
lines.append(f'  cLog2p1ErrSmall: Tb64u64 = (u:{fu(b64("0x1.d4p-62"))}); // 0x1.d4p-62')
lines.append(f'  cLog2p1ErrMain:  Tb64u64 = (u:{fu(b64("0x1.23p-68"))}); // 0x1.23p-68')

# LOG2_INV dint: C ex=12, pascoremath +1 → ex=13
# C: hi=0xb8aa3b295c17f0bb, lo=0xbe87fed0691d3e89, ex=12, sgn=0
lines.append(f'  cLog2p1Log2InvDint: TDInt64 = (hi:$B8AA3B295C17F0BB; lo:$BE87FED0691D3E89; ex:13; sgn:0);')

# Exception value used in cr_log2p1_accurate_tiny: 0x0.2c316a14459d8p-1022 (subnormal)
exc_tiny = b64('0x0.2c316a14459d8p-1022')
exc_tiny_b = b64('0x1.fe0e7458ac1f8p-1025')
lines.append(f'  cLog2p1AccTinyExc:  Tb64u64 = (u:{fu(exc_tiny)});  // 0x0.2c316a14459d8p-1022')
lines.append(f'  cLog2p1AccTinyExcB: Tb64u64 = (u:{fu(exc_tiny_b)}); // 0x1.fe0e7458ac1f8p-1025')

lines.append('')
with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f'Wrote {OUT} ({len(lines)} lines)')
