#!/usr/bin/env python3
"""Generate src/log_const.inc from core-math/src/binary64/log/{log.c, dint.h}.

Note: pas-core-math TDInt64 uses sin.c convention where significand is in
[0.5, 1) and ex is one greater than log.c's convention (where significand
is in [1, 2)). So we add +1 to every .ex field from log.c/dint.h.
"""
import re, struct, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG_C = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'log', 'log.c')
DINT_H = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'log', 'dint.h')
OUT = os.path.join(ROOT, 'src', 'inc_64', 'log_const_64.inc')

def b64(s):
    """Hex-float string -> uint64 bit pattern."""
    f = float.fromhex(s)
    return struct.unpack('<Q', struct.pack('<d', f))[0]

def fu(u):
    s = f"$%016X" % u
    # Wrap negative-bit-pattern (bit 63 set) with QWord() so FPC range-check
    # does not warn while parsing the literal as Int64.
    if u >= (1 << 63):
        return f"QWord({s})"
    return s

def slurp(p):
    with open(p) as f:
        return f.read()

def slice_array(text, name):
    # Extract everything between `{` after the array decl and the matching `};`
    m = re.search(rf'\b{re.escape(name)}\s*(?:\[[^\]]*\]\s*)+=\s*\{{', text)
    assert m, name
    i = m.end() - 1
    depth = 0
    j = i
    while j < len(text):
        if text[j] == '{':
            depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0:
                return text[i:j+1]
        j += 1
    raise SystemExit('mismatched braces')

# --------- log.c arrays ---------
src = slurp(LOG_C)

# _INVERSE: 363 hex-float doubles
inv_block = slice_array(src, '_INVERSE')
inv_vals = re.findall(r'0x[0-9a-fA-Fp.+\-]+', inv_block)
assert len(inv_vals) == 363, len(inv_vals)
INVERSE = [b64(v) for v in inv_vals]

# _LOG_INV: 363 entries of {h, l}
li_block = slice_array(src, '_LOG_INV')
# Each entry has two hex floats — capture pairs
pairs = re.findall(r'\{([^{}]+)\}', li_block)
assert len(pairs) == 363, len(pairs)
LOG_INV = []
for p in pairs:
    nums = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', p)
    assert len(nums) == 2, p
    LOG_INV.append((b64(nums[0]), b64(nums[1])))

# P[6]
p_block = slice_array(src, 'P')
pvals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', p_block)
assert len(pvals) == 6, len(pvals)
P_FAST = [b64(v) for v in pvals]

# --------- dint.h arrays ---------
dint = slurp(DINT_H)

def parse_dint_array(name):
    block = slice_array(dint, name)
    # Find each {hi, lo, ex, sgn} struct
    structs = re.findall(r'\{[^{}]*\}', block)
    out = []
    for s in structs:
        # Extract values as decimal/hex, allowing -ve
        d = {}
        for m in re.finditer(r'\.(\w+)\s*=\s*(-?0x[0-9a-fA-F]+|-?\d+)', s):
            v = m.group(2)
            n = int(v, 16) if v.lower().startswith('0x') or v.lower().startswith('-0x') else int(v)
            d[m.group(1)] = n
        out.append((d['hi'] & 0xFFFFFFFFFFFFFFFF, d['lo'] & 0xFFFFFFFFFFFFFFFF, d['ex'] + 1, d.get('sgn', 0)))
        # +1 for convention shift
    return out

INVERSE_2 = parse_dint_array('_INVERSE_2')
LOG_INV_2 = parse_dint_array('_LOG_INV_2')
P_2 = parse_dint_array('P_2')
N2 = len(INVERSE_2)
assert len(INVERSE_2) == len(LOG_INV_2), (len(INVERSE_2), len(LOG_INV_2))
assert len(P_2) == 13, len(P_2)

# LOG2 from dint.h has ex=-1 → +1 = 0
LOG2 = (0xb17217f7d1cf79ab, 0xc9e3b39803f2f6af, 0, 0)
M_ONE = (0x8000000000000000, 0, 1, 1)

# Fast-path log2_h, log2_l
log2_h_u = b64('0x1.62e42fefa38p-1')
log2_l_u = b64('0x1.ef35793c7673p-45')

# err = 0x1.b6p-69
err_u = b64('0x1.b6p-69')

# --------- emit ---------
lines = []
lines.append('// AUTO-GENERATED by tools/log_gen.py from core-math/src/binary64/log/{log.c,dint.h}')
lines.append('// Do not hand-edit; rerun tools/log_gen.py after upstream changes.')
lines.append('// Note: TDInt64 .ex is shifted by +1 vs log.c convention to match pascoremath.')
lines.append('')
lines.append('const')

# _INVERSE
lines.append('  cLogInverse: array[0..362] of Tb64u64 = (')
for i in range(0, 363, 4):
    chunk = INVERSE[i:i+4]
    s = ', '.join(f'(u:{fu(u)})' for u in chunk)
    sep = ',' if i + 4 < 363 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')

# _LOG_INV (h, l) flattened — store as two arrays for clarity
lines.append('  cLogInvH: array[0..362] of Tb64u64 = (')
for i in range(0, 363, 4):
    chunk = [h for (h, l) in LOG_INV[i:i+4]]
    s = ', '.join(f'(u:{fu(u)})' for u in chunk)
    sep = ',' if i + 4 < 363 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')
lines.append('  cLogInvL: array[0..362] of Tb64u64 = (')
for i in range(0, 363, 4):
    chunk = [l for (h, l) in LOG_INV[i:i+4]]
    s = ', '.join(f'(u:{fu(u)})' for u in chunk)
    sep = ',' if i + 4 < 363 else ''
    lines.append(f'    {s}{sep}')
lines.append('  );')
lines.append('')

# P[6] — Phase 6.2 Pillar B: lift to named Tb64u64 scalars (all reads are .f).
lines.append('  // cLogP fast-path polynomial — Pillar B: lifted to named Tb64u64 scalars.')
for i, u in enumerate(P_FAST):
    lines.append(f'  cLogP_{i}: Tb64u64 = (u:{fu(u)});')
lines.append('')

# log2_h, log2_l, err
lines.append(f'  cLogLog2h: Tb64u64 = (u:{fu(log2_h_u)}); // 0x1.62e42fefa38p-1')
lines.append(f'  cLogLog2l: Tb64u64 = (u:{fu(log2_l_u)}); // 0x1.ef35793c7673p-45')
lines.append(f'  cLogErr:   Tb64u64 = (u:{fu(err_u)});   // 0x1.b6p-69')
lines.append('')

# Refine-path TDInt64 arrays: emit as initialised constant arrays.
def fmt_dint(rec):
    hi, lo, ex, sgn = rec
    return f'(hi:{fu(hi)}; lo:{fu(lo)}; ex:{ex}; sgn:{sgn})'

lines.append(f'  cLogInverse2: array[0..{N2-1}] of TDInt64 = (')
for i in range(N2):
    sep = ',' if i + 1 < N2 else ''
    lines.append(f'    {fmt_dint(INVERSE_2[i])}{sep}')
lines.append('  );')
lines.append('')

lines.append(f'  cLogLogInv2: array[0..{N2-1}] of TDInt64 = (')
for i in range(N2):
    sep = ',' if i + 1 < N2 else ''
    lines.append(f'    {fmt_dint(LOG_INV_2[i])}{sep}')
lines.append('  );')
lines.append('')

lines.append('  cLogP2: array[0..12] of TDInt64 = (')
for i in range(13):
    sep = ',' if i + 1 < 13 else ''
    lines.append(f'    {fmt_dint(P_2[i])}{sep}')
lines.append('  );')
lines.append('')

lines.append(f'  cLogLog2Dint: TDInt64 = {fmt_dint(LOG2)};')
lines.append(f'  cLogMOneDint: TDInt64 = {fmt_dint(M_ONE)};')
lines.append('')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f'Wrote {OUT} ({len(lines)} lines)')
