#!/usr/bin/env python3
"""Generate src/pow_const.inc from core-math/src/binary64/pow/pow.h.

5.02b: pow.h has eight static tables —
  _INVERSE[182], _LOG_INV[182][2], T1[][2] (64 entries), T2[][2] (64 entries),
  P_1[6], Q_1[5].

Runtime-indexed tables (_INVERSE, _LOG_INV, T1, T2) are emitted as
  array[0..N] of Tb64u64
to dodge x87 codegen on FPC. Polynomial coefficients (P_1, Q_1) are
emitted as individual named scalars per the project rule "prefer named
Double constants over Double arrays" — they are accessed at compile-time
fixed indices in q_1/p_1, so this is safe.

5.02c/5.02d will append dint/qint pow tables to the same .inc file.
"""
import re, struct, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POW_H = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'pow', 'pow.h')
OUT = os.path.join(ROOT, 'src', 'pow_const.inc')

def b64(s):
    f = float.fromhex(s)
    return struct.unpack('<Q', struct.pack('<d', f))[0]

def fu(u):
    return f"$%016X" % u

def slurp(p):
    with open(p) as f:
        return f.read()

def slice_array(text, name):
    m = re.search(rf'\b{re.escape(name)}\s*(?:\[[^\]]*\]\s*)+=\s*\{{', text)
    assert m, name
    i = m.end() - 1
    depth = 0
    j = i
    while j < len(text):
        if text[j] == '{':
            depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0:
                return text[i:j+1]
        j += 1
    raise SystemExit('mismatched braces')

src = slurp(POW_H)

# _INVERSE: 182 doubles
inv_block = slice_array(src, '_INVERSE')
inv_vals = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', inv_block)
assert len(inv_vals) == 182, len(inv_vals)
INVERSE = [b64(v) for v in inv_vals]

# _LOG_INV: 182 pairs
li_block = slice_array(src, '_LOG_INV')
pairs = re.findall(r'\{([^{}]+)\}', li_block)
assert len(pairs) == 182, len(pairs)
LOG_INV = []
for p in pairs:
    nums = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+|\b0\b', p)
    assert len(nums) == 2, p
    h = b64(nums[0]) if nums[0].startswith(('0x','-0x')) else 0
    l = b64(nums[1]) if nums[1].startswith(('0x','-0x')) else 0
    LOG_INV.append((h, l))

def parse_pair_table(name):
    block = slice_array(src, name)
    pairs = re.findall(r'\{([^{}]+)\}', block)
    out = []
    for p in pairs:
        nums = re.findall(r'-?0x[0-9a-fA-Fp.+\-]+|\b0\b', p)
        assert len(nums) == 2, p
        h = b64(nums[0]) if nums[0].startswith(('0x','-0x')) else 0
        l = b64(nums[1]) if nums[1].startswith(('0x','-0x')) else 0
        out.append((h, l))
    return out

T1 = parse_pair_table('T1')
T2 = parse_pair_table('T2')
assert len(T1) == 64
assert len(T2) == 64

# P_1[6], Q_1[5]
p1_block = slice_array(src, 'P_1')
P1 = [b64(v) for v in re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', p1_block)]
assert len(P1) == 6, len(P1)

q1_block = slice_array(src, 'Q_1')
Q1 = [b64(v) for v in re.findall(r'-?0x[0-9a-fA-Fp.+\-]+', q1_block)]
assert len(Q1) == 5, len(Q1)

# ----------------------------- emit -----------------------------
out = []
out.append("// AUTO-GENERATED by tools/pow_gen.py from core-math/src/binary64/pow/pow.h")
out.append("// Do not hand-edit; rerun tools/pow_gen.py after upstream changes.")
out.append("// 5.02b: pow.h fast-path tables (binary64 pow).")
out.append("")
out.append("const")

def emit_array(name, vals, per_line=4):
    out.append(f"  {name}: array[0..{len(vals)-1}] of Tb64u64 = (")
    for i in range(0, len(vals), per_line):
        chunk = vals[i:i+per_line]
        line = ', '.join(f"(u:{fu(v)})" for v in chunk)
        sep = ',' if i + per_line < len(vals) else ''
        out.append(f"    {line}{sep}")
    out.append("  );")
    out.append("")

emit_array("cPowInverse", INVERSE)
emit_array("cPowLogInvHi", [h for (h, _) in LOG_INV])
emit_array("cPowLogInvLo", [l for (_, l) in LOG_INV])
emit_array("cPowT1Hi", [h for (h, _) in T1])
emit_array("cPowT1Lo", [l for (_, l) in T1])
emit_array("cPowT2Hi", [h for (h, _) in T2])
emit_array("cPowT2Lo", [l for (_, l) in T2])

# P_1: degree 3..8, indices 0..5
out.append("  // P_1: log(1+x)-x+x^2/2 polynomial, degrees 3..8")
for i, v in enumerate(P1):
    out.append(f"  cPowP1_{i}: Tb64u64 = (u:{fu(v)});")
out.append("")
# Q_1: degrees 0..4, indices 0..4
out.append("  // Q_1: exp(x) polynomial, degrees 0..4")
for i, v in enumerate(Q1):
    out.append(f"  cPowQ1_{i}: Tb64u64 = (u:{fu(v)});")
out.append("")

# =====================================================================
# 5.02c: dint-level pow tables from pow/dint.h
# =====================================================================
DINT_H = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'pow', 'dint.h')
dint_src = slurp(DINT_H)

def parse_dint_array(text, name):
    block = slice_array(text, name)
    structs = re.findall(r'\{[^{}]*\}', block)
    out_list = []
    for s in structs:
        # Extract .hi, .lo (hex), .ex (decimal, possibly negative), .sgn
        hi_m = re.search(r'\.hi\s*=\s*(0x[0-9a-fA-F]+)', s)
        lo_m = re.search(r'\.lo\s*=\s*(0x[0-9a-fA-F]+)', s)
        ex_m = re.search(r'\.ex\s*=\s*(-?\d+)', s)
        sg_m = re.search(r'\.sgn\s*=\s*(0x[0-9a-fA-F]+|\d+)', s)
        hi = int(hi_m.group(1), 16) if hi_m else 0
        lo = int(lo_m.group(1), 16) if lo_m else 0
        ex = int(ex_m.group(1))
        sgn = int(sg_m.group(1), 0) if sg_m else 0
        out_list.append((hi, lo, ex, sgn))
    return out_list

INV21 = parse_dint_array(dint_src, '_INVERSE_2_1')
INV22 = parse_dint_array(dint_src, '_INVERSE_2_2')
LI21  = parse_dint_array(dint_src, '_LOG_INV_2_1')
LI22  = parse_dint_array(dint_src, '_LOG_INV_2_2')
T12   = parse_dint_array(dint_src, 'T1_2')
T22   = parse_dint_array(dint_src, 'T2_2')
P2    = parse_dint_array(dint_src, 'P_2')
Q2    = parse_dint_array(dint_src, 'Q_2')

assert len(INV21) == 92,  len(INV21)
assert len(INV22) == 129, len(INV22)
assert len(LI21)  == 92,  len(LI21)
assert len(LI22)  == 129, len(LI22)
assert len(T12)   == 64,  len(T12)
assert len(T22)   == 64,  len(T22)
assert len(P2)    == 9,   len(P2)
assert len(Q2)    == 8,   len(Q2)

EX_OFFSET = 1  # Pascal TDInt64 convention: .ex shifted by +1 vs pow/dint.h

def emit_dint_array(name, vals):
    out.append(f"  {name}: array[0..{len(vals)-1}] of TDInt64 = (")
    for i, (hi, lo, ex, sgn) in enumerate(vals):
        sep = ',' if i + 1 < len(vals) else ''
        out.append(f"    (hi:${hi:016X}; lo:${lo:016X}; ex:{ex+EX_OFFSET}; sgn:{sgn}){sep}")
    out.append("  );")
    out.append("")

out.append("// ---- 5.02c: dint-level pow tables (from pow/dint.h) ----")
out.append("// .ex shifted by +1 vs C convention to match Pascal TDInt64")
out.append("")
emit_dint_array("cPowInverse21", INV21)
emit_dint_array("cPowInverse22", INV22)
emit_dint_array("cPowLogInv21",  LI21)
emit_dint_array("cPowLogInv22",  LI22)
emit_dint_array("cPowT12",       T12)
emit_dint_array("cPowT22",       T22)

# P_2 (9 entries) and Q_2 (8 entries) — split into named scalars per project rule.
out.append("  // P_2: log(1+z) polynomial for slow path (degrees from highest to constant)")
for i, (hi, lo, ex, sgn) in enumerate(P2):
    out.append(f"  cPowP2_{i}: TDInt64 = (hi:${hi:016X}; lo:${lo:016X}; ex:{ex+EX_OFFSET}; sgn:{sgn});")
out.append("")
out.append("  // Q_2: exp(z) polynomial for slow path (degrees from highest to constant)")
for i, (hi, lo, ex, sgn) in enumerate(Q2):
    out.append(f"  cPowQ2_{i}: TDInt64 = (hi:${hi:016X}; lo:${lo:016X}; ex:{ex+EX_OFFSET}; sgn:{sgn});")
out.append("")

# =====================================================================
# 5.02d: qint-level pow tables from pow/qint.h
# =====================================================================
QINT_H = os.path.join(ROOT, '..', 'core-math', 'src', 'binary64', 'pow', 'qint.h')
qint_src = slurp(QINT_H)

def parse_qint_array(text, name):
    block = slice_array(text, name)
    structs = re.findall(r'\{[^{}]*\}', block)
    out_list = []
    for s in structs:
        def hx(field):
            m = re.search(rf'\.{field}\s*=\s*(0x[0-9a-fA-F]+)', s)
            return int(m.group(1), 16) if m else 0
        ex_m = re.search(r'\.ex\s*=\s*(-?\d+)', s)
        sg_m = re.search(r'\.sgn\s*=\s*(0x[0-9a-fA-F]+|\d+)', s)
        ex  = int(ex_m.group(1))
        sgn = int(sg_m.group(1), 0) if sg_m else 0
        out_list.append((hx('hh'), hx('hl'), hx('lh'), hx('ll'), ex, sgn))
    return out_list

INV31 = parse_qint_array(qint_src, '_INVERSE_3_1')
INV32 = parse_qint_array(qint_src, '_INVERSE_3_2')
LI31  = parse_qint_array(qint_src, '_LOG_INV_3_1')
LI32  = parse_qint_array(qint_src, '_LOG_INV_3_2')
T13   = parse_qint_array(qint_src, 'T1_3')
T23   = parse_qint_array(qint_src, 'T2_3')
P3    = parse_qint_array(qint_src, 'P_3')
Q3    = parse_qint_array(qint_src, 'Q_3')

assert len(INV31) == 92,  len(INV31)
assert len(INV32) == 129, len(INV32)
assert len(LI31)  == 92,  len(LI31)
assert len(LI32)  == 129, len(LI32)
assert len(T13)   == 64,  len(T13)
assert len(T23)   == 64,  len(T23)
assert len(P3)    == 18,  len(P3)
assert len(Q3)    == 15,  len(Q3)

# qint convention: pas-core-math QINT_ONE.ex = 0 == C ONE_Q.ex = 0.
# No ex offset for qint tables.

def emit_qint_array(name, vals):
    out.append(f"  {name}: array[0..{len(vals)-1}] of TQInt64 = (")
    for i, (hh, hl, lh, ll, ex, sgn) in enumerate(vals):
        sep = ',' if i + 1 < len(vals) else ''
        out.append(
            f"    (r0:${hh:016X}; r1:${hl:016X}; r2:${lh:016X}; r3:${ll:016X}; "
            f"ex:{ex}; sgn:{sgn}){sep}"
        )
    out.append("  );")
    out.append("")

out.append("// ---- 5.02d: qint-level pow tables (from pow/qint.h) ----")
out.append("// qint .ex matches C convention exactly (no offset, unlike dint).")
out.append("// C qint64_t {hh,hl,lh,ll} maps to Pascal TQInt64 {r0,r1,r2,r3}.")
out.append("")
emit_qint_array("cPowInverse31", INV31)
emit_qint_array("cPowInverse32", INV32)
emit_qint_array("cPowLogInv31",  LI31)
emit_qint_array("cPowLogInv32",  LI32)
emit_qint_array("cPowT13",       T13)
emit_qint_array("cPowT23",       T23)

out.append("  // P_3: log(1+z) very-slow-path polynomial (degrees 18..1, high to low)")
for i, (hh, hl, lh, ll, ex, sgn) in enumerate(P3):
    out.append(
        f"  cPowP3_{i}: TQInt64 = (r0:${hh:016X}; r1:${hl:016X}; "
        f"r2:${lh:016X}; r3:${ll:016X}; ex:{ex}; sgn:{sgn});"
    )
out.append("")
out.append("  // Q_3: exp(z) very-slow-path polynomial (degrees 14..0, high to low)")
for i, (hh, hl, lh, ll, ex, sgn) in enumerate(Q3):
    out.append(
        f"  cPowQ3_{i}: TQInt64 = (r0:${hh:016X}; r1:${hl:016X}; "
        f"r2:${lh:016X}; r3:${ll:016X}; ex:{ex}; sgn:{sgn});"
    )
out.append("")

with open(OUT, 'w') as f:
    f.write('\n'.join(out))
print(f"Wrote {OUT}")
print(f"  pow.h: cPowInverse[{len(INVERSE)}], cPowLogInvHi/Lo[{len(LOG_INV)}],")
print(f"         cPowT1Hi/Lo[{len(T1)}], cPowT2Hi/Lo[{len(T2)}],")
print(f"         cPowP1_0..{len(P1)-1}, cPowQ1_0..{len(Q1)-1}")
print(f"  dint.h: cPowInverse21[{len(INV21)}], cPowInverse22[{len(INV22)}],")
print(f"          cPowLogInv21[{len(LI21)}],  cPowLogInv22[{len(LI22)}],")
print(f"          cPowT12[{len(T12)}], cPowT22[{len(T22)}],")
print(f"          cPowP2_0..{len(P2)-1}, cPowQ2_0..{len(Q2)-1}")
print(f"  qint.h: cPowInverse31[{len(INV31)}], cPowInverse32[{len(INV32)}],")
print(f"          cPowLogInv31[{len(LI31)}],  cPowLogInv32[{len(LI32)}],")
print(f"          cPowT13[{len(T13)}], cPowT23[{len(T23)}],")
print(f"          cPowP3_0..{len(P3)-1}, cPowQ3_0..{len(Q3)-1}")
