#!/usr/bin/env python3
"""Generate src/tgamma_const.inc from core-math tgamma.c.

Extracts every static const double table in tgamma.c, plus the B[] short/ushort
pair table used by as_logd, into a single .inc file with Tb64u64 / Word / SmallInt
arrays. Branch-local (function-scope) tables in as_tgamma_accurate are emitted
as cTGAcc<i>Ch / cTGAcc<i>Cl, indexed 0..8 in the same order as the C if/else
chain (i>159, i>127, i>95, i>63, i>31, i>25, i>15, i>7, else).
"""
import re, struct, os, sys

SRC = os.path.join(os.path.dirname(__file__), '..', '..', 'core-math', 'src',
                   'binary64', 'tgamma', 'tgamma.c')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'tgamma_const.inc')

with open(SRC) as f:
    text = f.read()

# Strip block comments and line comments
text_nc = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
text_nc = re.sub(r'//[^\n]*', '', text_nc)

HEX = re.compile(r'-?0x[0-9a-fA-F.]+p[+-]?\d+')

def to_u64(s):
    v = float.fromhex(s)
    b = struct.pack('<d', v)
    return struct.unpack('<Q', b)[0], v

lines = ["// Auto-generated by tools/tgamma_gen.py — do not edit by hand.",
         "// Source: core-math/src/binary64/tgamma/tgamma.c",
         ""]

def emit_2d(name, rows, comment=''):
    R, C = len(rows), len(rows[0])
    if comment:
        lines.append(f"  // {name} {comment}")
    lines.append(f"  {name}: array[0..{R-1},0..{C-1}] of Tb64u64 = (")
    for i, row in enumerate(rows):
        ents = []
        for n in row:
            u, _ = to_u64(n)
            ents.append(f"(u:${u:016X})")
        sep = ',' if i < R-1 else ''
        lines.append(f"    ({', '.join(ents)}){sep}")
    lines.append("  );")
    lines.append("")

def emit_1d(name, nums, comment=''):
    if comment:
        lines.append(f"  // {name} {comment}")
    lines.append(f"  {name}: array[0..{len(nums)-1}] of Tb64u64 = (")
    for i, n in enumerate(nums):
        u, _ = to_u64(n)
        sep = ',' if i < len(nums)-1 else ''
        lines.append(f"    (u:${u:016X}){sep}")
    lines.append("  );")
    lines.append("")

def find_block_after(marker, name, expect_pairs):
    """Find a `static const double NAME[...][2]` (if expect_pairs=2) or
    `static const double NAME[...]` (if 1) appearing AFTER the given marker text
    in the source. Returns body string."""
    idx = text_nc.find(marker)
    assert idx >= 0, f"marker {marker!r} not found"
    sub = text_nc[idx:]
    if expect_pairs == 2:
        m = re.search(rf'static const double {name}\[[^\]]*\]\[2\]\s*=\s*\{{(.*?)\}};',
                      sub, re.S)
    else:
        m = re.search(rf'static const double {name}\[[^\]]*\]\s*=\s*\{{(.*?)\}};',
                      sub, re.S)
    assert m, f"{name} after {marker!r} not found"
    return m.group(1)

def parse_pairs(body):
    rows = re.findall(r'\{([^{}]*)\}', body)
    out = []
    for r in rows:
        nums = HEX.findall(r)
        assert len(nums) == 2, (r, nums)
        out.append(nums)
    return out

def parse_triples(body):
    rows = re.findall(r'\{([^{}]*)\}', body)
    out = []
    for r in rows:
        nums = HEX.findall(r)
        assert len(nums) == 3, (r, nums)
        out.append(nums)
    return out

def parse_flat(body):
    return HEX.findall(body)

# ---- 1) database (3 cols) ----
m = re.search(r'static const double db\[\]\[3\]\s*=\s*\{(.*?)\};',
              text_nc[text_nc.find('as_tgamma_database'):], re.S)
db_rows = parse_triples(m.group(1))
print(f"db: {len(db_rows)} rows", file=sys.stderr)
emit_2d('cTGDb', db_rows, '[N][3] worst-case database (input, hi, lo)')

# ---- 2) as_tgamma_accurate |x|<0.25 cc ----
acc_idx = text_nc.find('as_tgamma_accurate')
acc_body = text_nc[acc_idx:]
m = re.search(r'if\(__builtin_fabs\(x\)<0\.25\)\{\s*static const double cc\[\]\[2\]\s*=\s*\{(.*?)\};\s*static const double c\[\]\s*=\s*\{(.*?)\};',
              acc_body, re.S)
assert m
cc_acc_small = parse_pairs(m.group(1))
c_acc_small = parse_flat(m.group(2))
print(f"acc small cc: {len(cc_acc_small)}, c: {len(c_acc_small)}", file=sys.stderr)
emit_2d('cTGAccSmallCc', cc_acc_small, '[28][2] accurate-path |x|<0.25 dd polynomial')
emit_1d('cTGAccSmallC', c_acc_small, '[8] accurate-path |x|<0.25 single polynomial')

# ---- 3) eight branch tables in as_tgamma_accurate ----
# Each branch has `static const double ch[] = {...}; static const double cl[][2] = {...};`
# Collect them all in the order they appear.
branches = []
pos = m.end()
branch_re = re.compile(
    r'static const double ch\[\]\s*=\s*\{([^}]*?)\};\s*'
    r'static const double cl\[\]\[2\]\s*=\s*\{(.*?)\};',
    re.S)
for bm in branch_re.finditer(acc_body, pos):
    ch = parse_flat(bm.group(1))
    cl = parse_pairs(bm.group(2))
    branches.append((ch, cl))
print(f"branches: {[(len(c), len(l)) for c,l in branches]}", file=sys.stderr)
assert len(branches) == 9, len(branches)
for i, (ch, cl) in enumerate(branches):
    emit_1d(f'cTGAcc{i}Ch', ch, f'[{len(ch)}] branch {i} ch[]')
    emit_2d(f'cTGAcc{i}Cl', cl, f'[{len(cl)}][2] branch {i} cl[]')

# ---- 4) cr_tgamma small-|x| tables (|x|<0.25) ----
cr_idx = text_nc.find('double cr_tgamma(double x)')
cr_body = text_nc[cr_idx:]
# After the |x|<0x1p-112 fast block, there are static const cc and c
m = re.search(r'static const double cc\[\]\[2\]\s*=\s*\{(.*?)\};\s*static const double c\[\]\s*=\s*\{(.*?)\};',
              cr_body, re.S)
assert m
cc_cr_small = parse_pairs(m.group(1))
c_cr_small = parse_flat(m.group(2))
print(f"cr small cc: {len(cc_cr_small)}, c: {len(c_cr_small)}", file=sys.stderr)
emit_2d('cTGSmallCc', cc_cr_small, '[5][2] cr_tgamma |x|<0.25 dd polynomial')
emit_1d('cTGSmallC', c_cr_small, '[16] cr_tgamma |x|<0.25 single polynomial')

# Then later, cr_tgamma main path 0.25<=|x|<=4 has cc and c
pos2 = m.end()
m = re.search(r'static const double cc\[\]\[2\]\s*=\s*\{(.*?)\};\s*static const double c\[\]\s*=\s*\{(.*?)\};',
              cr_body[pos2:], re.S)
assert m
cc_cr_main = parse_pairs(m.group(1))
c_cr_main = parse_flat(m.group(2))
print(f"cr main cc: {len(cc_cr_main)}, c: {len(c_cr_main)}", file=sys.stderr)
emit_2d('cTGMainCc', cc_cr_main, '[18][2] cr_tgamma 0.25<=x<=4 dd polynomial')
emit_1d('cTGMainC', c_cr_main, '[18] cr_tgamma 0.25<=x<=4 single polynomial')

# ---- 5) as_logd: B (struct), r1, r2, l1, l2, c ----
logd_idx = text_nc.find('double as_logd')
logd_body = text_nc[logd_idx:]

m = re.search(r'static const struct\s*\{ushort c0;\s*short c1;\}\s*B\[\]\s*=\s*\{(.*?)\};',
              logd_body, re.S)
assert m
B_pairs = re.findall(r'\{\s*(-?\d+)\s*,\s*(-?\d+)\s*\}', m.group(1))
print(f"B: {len(B_pairs)}", file=sys.stderr)
assert len(B_pairs) == 32

# Emit B as a record with c0 (Word) and c1 (SmallInt)
lines.append('  cTGLogB: array[0..31] of record c0: Word; c1: SmallInt; end = (')
for i, (a, b) in enumerate(B_pairs):
    sep = ',' if i < 31 else ''
    lines.append(f'    (c0:{a}; c1:{b}){sep}')
lines.append('  );')
lines.append('')

m = re.search(r'static const double r1\[\]\s*=\s*\{(.*?)\};', logd_body, re.S)
r1 = parse_flat(m.group(1))
m = re.search(r'static const double r2\[\]\s*=\s*\{(.*?)\};', logd_body, re.S)
r2 = parse_flat(m.group(1))
print(f"r1: {len(r1)}, r2: {len(r2)}", file=sys.stderr)
emit_1d('cTGLogR1', r1, '[33]')
emit_1d('cTGLogR2', r2, '[33]')

m = re.search(r'static const double l1\[\]\[2\]\s*=\s*\{(.*?)\};', logd_body, re.S)
l1 = parse_pairs(m.group(1))
m = re.search(r'static const double l2\[\]\[2\]\s*=\s*\{(.*?)\};', logd_body, re.S)
l2 = parse_pairs(m.group(1))
print(f"l1: {len(l1)}, l2: {len(l2)}", file=sys.stderr)
emit_2d('cTGLogL1', l1, '[33][2]')
emit_2d('cTGLogL2', l2, '[33][2]')

m = re.search(r'double c\[\]\s*=\s*\{(-0x1\.fffffffffffd3p-2.*?)\};',
              logd_body, re.S)
assert m, "as_logd c[] not found"
c_logd = parse_flat(m.group(1))
print(f"logd c: {len(c_logd)}", file=sys.stderr)
emit_1d('cTGLogC', c_logd, '[4]')

# ---- 6) sinpid: st, c, c0, s, s0 ----
m = re.search(r'static const double st\[\]\[2\]\s*=\s*\{(.*?)\};', text_nc, re.S)
st = parse_pairs(m.group(1))
print(f"st: {len(st)}", file=sys.stderr)
emit_2d('cTGSt', st, '[65][2]')

# Inside as_sinpid: c[4], s[4]
sinp_idx = text_nc.find('static double as_sinpid')
sinp_body = text_nc[sinp_idx:]
m = re.search(r'double c\[\]\s*=\s*\{(.*?)\};', sinp_body, re.S)
sinp_c = parse_flat(m.group(1))
m = re.search(r'double c0\s*=\s*(-?0x[0-9a-fA-F.]+p[+-]?\d+)\s*;', sinp_body)
sinp_c0 = m.group(1)
m = re.search(r'double s\[\]\s*=\s*\{(.*?)\};', sinp_body, re.S)
sinp_s = parse_flat(m.group(1))
m = re.search(r'double s0\s*=\s*(-?0x[0-9a-fA-F.]+p[+-]?\d+)\s*;', sinp_body)
sinp_s0 = m.group(1)
print(f"sinp_c: {len(sinp_c)} sinp_s: {len(sinp_s)}", file=sys.stderr)

emit_1d('cTGSinpC', sinp_c, '[4]')
u, _ = to_u64(sinp_c0)
lines.append(f'  cTGSinpC0: Tb64u64 = (u:${u:016X});')
lines.append('')
emit_1d('cTGSinpS', sinp_s, '[4]')
u, _ = to_u64(sinp_s0)
lines.append(f'  cTGSinpS0: Tb64u64 = (u:${u:016X});')
lines.append('')

# ---- 7) expd: E0, E1, c[][2] ----
m = re.search(r'static const double E0\[\]\[2\]\s*=\s*\{(.*?)\};', text_nc, re.S)
E0 = parse_pairs(m.group(1))
m = re.search(r'static const double E1\[\]\[2\]\s*=\s*\{(.*?)\};', text_nc, re.S)
E1 = parse_pairs(m.group(1))
emit_2d('cTGExpE0', E0, '[32][2]')
emit_2d('cTGExpE1', E1, '[32][2]')

expd_idx = text_nc.find('static double as_expd')
expd_body = text_nc[expd_idx:]
m = re.search(r'static const double c\[\]\[2\]\s*=\s*\{(.*?)\};', expd_body, re.S)
expd_c = parse_pairs(m.group(1))
emit_2d('cTGExpC', expd_c, '[5][2]')

# ---- 8) lgamma_asym: two c[][2] tables ----
lg_idx = text_nc.find('as_lgamma_asym(double xh')
lg_body = text_nc[lg_idx:]
# Find both static const double c[][2] = {...}; in lg_body — first is xh>11.5 (8 entries),
# second is else (13 entries)
matches = list(re.finditer(r'static const double c\[\]\[2\]\s*=\s*\{(.*?)\};', lg_body, re.S))
assert len(matches) == 2, len(matches)
lg_big = parse_pairs(matches[0].group(1))
lg_sml = parse_pairs(matches[1].group(1))
print(f"lg_big: {len(lg_big)} lg_sml: {len(lg_sml)}", file=sys.stderr)
emit_2d('cTGLgBig', lg_big, '[8][2] xh > 11.5 asymptotic coeffs')
emit_2d('cTGLgSml', lg_sml, '[13][2] xh <= 11.5 asymptotic coeffs')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"wrote {OUT}: {sum(1 for _ in open(OUT))} lines")
